const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((q,r)=>fs.readFile(path.join(root,q.url==='/'?'index.html':q.url),(err,data)=>{r.setHeader('Content-Type',q.url.endsWith('.png')?'image/png':q.url.endsWith('.js')?'application/javascript':'text/html');r.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.PWA_BROWSER});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await context.addInitScript(require('./movement-test-helpers.cjs').clock);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const state=()=>page.evaluate(()=>__dofTest.state()),snap=()=>page.evaluate(()=>__dofTest.serializeRun()),boss=()=>page.evaluate(()=>__dofTest.boss()),resume=async()=>{await page.reload();await page.locator('#continueRun').click()};
 async function prepare(roll,{bossHp=3,weak=false,health=3,shield=false,items=[],bargain=false}={}){await page.evaluate(o=>{const t=__dofTest;t.newRun();t.setFloor(25);for(const id of o.items){t.acquireTrinket(id);t.closeItemCard()}if(o.bargain){t.setConsumable('bargain');t.useConsumable(true)}t.setVitals(o.health,o.shield);t.setCombo(5);t.setCurrent(t.state().exitId);t.setRoomFixture(t.state().exitId,{searched:true});if(o.weak)t.applyCondition('weakness');t.openBossCard(t.state().exitId);Math.random=()=>((o.roll-1)/6)+.001;t.beginBossFight();const b=t.boss();b.hp=o.bossHp;t.setRoomFixture(t.state().exitId,{boss:b});t.revealOutcome()}, {roll,bossHp,weak,health,shield,items,bargain})}
 // Wretch is a separate acquired identity with exactly the Basic roll mechanics.
 for(const roll of [1,2,3,4,5,6]){const outcomes=[];for(const kind of ['basic','wretch']){outcomes.push(await page.evaluate(({roll,kind})=>{const t=__dofTest;t.newRun();t.setVitals(3,false);t.setCombo(5);t.setMonster(kind);const preview=t.previewOutcome('monster',roll,kind);t.resolveDice('monster',roll);const s=t.state();return{preview,hp:s.hp,gold:s.gold,combo:s.combo,conditions:s.conditions}}, {roll,kind}))}assert.deepEqual(outcomes[1],outcomes[0])}
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.showDice('monster','wretch')});assert((await page.evaluate(()=>__dofTest.codex())).discovered['creature:wretch']);
 // The existing loader safely performs the one condition-key rename.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.applyCondition('weakness');const s=t.serializeRun();s.run.conditions.sickness=s.run.conditions.weakness;delete s.run.conditions.weakness;localStorage.setItem('dof.activeRun',JSON.stringify(s));const loaded=t.loadRun();if(!loaded||loaded.run.conditions.weakness!==10||loaded.run.conditions.sickness)throw Error('old condition rename')});
 // Boss sensing uses the same living definition without revealing memory.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setFloor(25);t.acquireTrinket('eye');t.closeItemCard();const s=t.serializeRun(),r=s.floor.rooms[s.floor.exitId];t.setCurrent(r.links[0]);t.applyCondition('amnesia');if(!t.sensesLiving(r)||!t.creatureDefinition('basic',r).living)throw Error('living Boss sense');t.setRoomFixture(r.id,{boss:Object.assign({},r.boss,{hp:0,state:'defeated'})});if(t.sensesLiving(t.serializeRun().floor.rooms[r.id]))throw Error('defeated Boss sensed')});
 console.log('PASS Wretch Basic-table parity/Archive identity, Weakness loader key rename and living Boss sensing during Amnesia');
 // Actual arrival discovers the boss, but declining leaves exploration and descent safely separate.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setFloor(25);const s=t.state(),parent=s.rooms[s.exitId].links[0];t.setCurrent(parent);t.setRoomFixture(parent,{event:"empty",eventResolved:true,searched:true});window.bossParent=parent;t.enter(s.exitId);walkTick()});assert.equal((await boss()).state,'unresolved');assert((await page.evaluate(()=>__dofTest.codex())).discovered['creature:general']);assert.equal(await page.locator('#contentAction').innerText(),'FIGHT');assert.equal(await page.locator('.itemChoicePanel button:visible').count(),1);
 let b=await page.locator('#contentAction').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForTimeout(120);await page.mouse.up();assert.equal((await boss()).state,'unresolved');assert(await page.locator('#itemChoice').isVisible());await page.evaluate(()=>__dofTest.saveRun());await resume();assert.equal((await boss()).state,'unresolved');const frame=await page.locator('.itemChoicePanel').boundingBox();await page.mouse.move(frame.x+frame.width/2,frame.y+frame.height*.38);await page.mouse.down();await page.mouse.move(frame.x+frame.width/2,frame.y+frame.height*.38+120,{steps:8});await page.mouse.up();await page.waitForTimeout(260);assert(!await page.locator('#itemChoice').isVisible());assert.equal(await page.evaluate(()=>__dofTest.descend()),false);await page.evaluate(()=>{__dofTest.enter(__dofTest.state().rooms[__dofTest.state().exitId].links[0]);walkTick()});assert.equal((await state()).currentId,await page.evaluate(()=>__dofTest.state().rooms[__dofTest.state().exitId].links[0]));await page.evaluate(()=>{__dofTest.enter(__dofTest.state().exitId);walkTick()});
 await require('./card-hold-helpers.cjs').hold(page,'#contentAction');assert.equal((await boss()).state,'active');assert.equal((await boss()).round,1);assert.equal(await page.evaluate(()=>__dofTest.enter(__dofTest.state().rooms[__dofTest.state().exitId].links[0])),false);assert.equal(await page.evaluate(()=>__dofTest.showCodex()),false);assert.equal(await page.evaluate(()=>__dofTest.descend()),false);assert(await page.locator('#consumableSlot').isDisabled());
 await resume();assert.equal((await boss()).state,'active');assert.equal((await snap()).pending.encounter.type,'boss');assert.equal(await page.evaluate(()=>__dofTest.enter(__dofTest.state().rooms[__dofTest.state().currentId].links[0])),false);
 console.log('PASS actual terminal arrival, Archive encounter discovery, incomplete/full FIGHT holds, retreat before commitment and reload-locked fight');
 for(const roll of [1,2,3,4,5,6]){
  await prepare(roll);const before=await snap(),out=before.pending.encounter.preview;assert.equal(before.floor.rooms[before.floor.exitId].boss.hp,3);assert.equal(before.run.hp,3);assert.deepEqual(before.run.conditions,{});assert.equal(out.after.hp,roll<=3?2:3);assert.equal(out.after.bossHp,roll>=4?(roll===6?1:2):3);assert.equal(out.after.conditions.weakness,roll===1?10:undefined);
  await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await state()).hp,out.after.hp);assert.equal((await boss()).hp,out.after.bossHp);assert.deepEqual((await state()).conditions,out.after.conditions);assert.equal((await boss()).state,'active');assert.equal((await boss()).round,2);assert.equal((await snap()).pending.encounter.phase,'ready');const committed=await snap();await page.evaluate(()=>__dofTest.continueEncounter());assert.deepEqual((await snap()).run,committed.run);assert.equal((await boss()).round,2);
 }
 await prepare(4);const roundFrame=await page.locator('.encounterPanel').boundingBox();await page.mouse.move(roundFrame.x+roundFrame.width/2,roundFrame.y+roundFrame.height*.38);await page.mouse.down();await page.mouse.move(roundFrame.x+roundFrame.width/2,roundFrame.y+roundFrame.height*.38+120,{steps:8});await page.mouse.up();await page.waitForTimeout(260);assert.equal((await boss()).hp,2);assert.equal((await boss()).round,2);assert.equal((await snap()).pending.encounter.phase,'ready');assert(await page.locator('#diceOverlay').isVisible());
 const valid=await snap();assert(await page.evaluate(s=>__dofTest.validateSave(s),valid));const broken=JSON.parse(JSON.stringify(valid));broken.floor.rooms[broken.floor.exitId].boss.hp=4;assert.equal(await page.evaluate(s=>__dofTest.validateSave(s),broken),false);
 for(const hp of [2,1]){await prepare(6,{bossHp:hp});await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await boss()).hp,0);assert.equal((await boss()).state,'defeated');assert.equal((await state()).floorNo,25);assert.equal((await snap()).pending.encounter.phase,'resolved');await resume();assert.equal((await boss()).state,'defeated');await page.evaluate(()=>__dofTest.continueEncounter());assert.equal(await page.evaluate(()=>__dofTest.descend()),true);assert.equal((await state()).floorNo,26)}
 await prepare(1,{weak:true});assert.equal((await snap()).pending.encounter.preview.after.hp,1);await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await state()).hp,1);assert.equal((await state()).conditions.weakness,10);
 for(const protection of ['shield','bargain','doll']){await prepare(2,{weak:true,health:1,shield:protection==='shield',bargain:protection==='bargain',items:protection==='doll'?['doll']:[]});const p=(await snap()).pending.encounter.preview;await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await state()).hp,p.after.hp);assert(!(await state()).conditions.weakness);assert(!(await state()).gameOver)}
 await prepare(4,{health:2,items:['blood']});await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await state()).hp,2);assert(!(await state()).relics.floorUsed.blood);
 await prepare(6,{bossHp:1,health:2,items:['blood','horseshoe']});const p=(await snap()).pending.encounter.preview;await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await state()).hp,3);assert((await state()).relics.floorUsed.blood);assert.equal((await state()).gold,p.after.gold);
 await prepare(6,{bossHp:1,health:3,items:['blood']});await page.evaluate(()=>__dofTest.continueEncounter());assert(!(await state()).relics.floorUsed.blood);
 console.log('PASS six exact tables, non-negative Boss HP, hit-then-Weakness ordering, existing Weakness/protection rescue, Blood only at useful defeat, Horseshoe critical and deliberate descent');
 // Reroll/reload preserves the original and reserves exactly one final outcome each round.
 for(const roll of [1,4]){await prepare(roll);let pending=(await snap()).pending.encounter;await resume();assert.deepEqual((await snap()).pending.encounter,pending);assert.deepEqual((await state()).conditions,{});assert.equal((await boss()).hp,3);await page.waitForSelector('#rerollButton:not([hidden])');await page.evaluate(()=>Math.random=()=>.99);await require('./card-hold-helpers.cjs').hold(page,'#rerollButton');let final=(await snap()).pending.encounter;assert.equal(final.roll,6);assert(final.rerollUsed);assert.equal((await state()).combo,pending.offer.after);await resume();assert.equal((await snap()).pending.encounter.roll,6);assert.equal((await boss()).hp,3);await page.evaluate(()=>__dofTest.revealOutcome());assert.equal(await page.evaluate(()=>__dofTest.canReroll()),false);await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await boss()).hp,1);assert.deepEqual((await state()).conditions,{});const next=(await snap()).pending.encounter;await resume();assert.equal((await boss()).hp,1);assert.equal((await snap()).pending.encounter.roll,next.roll);await page.evaluate(()=>__dofTest.revealOutcome());assert.equal(await page.evaluate(()=>__dofTest.canReroll()),true)}
 await prepare(1);await page.evaluate(()=>__dofTest.continueEncounter());await resume();assert.equal((await state()).hp,2);assert.equal((await state()).conditions.weakness,10);assert.equal((await boss()).hp,3);
 await prepare(2,{health:1});await page.evaluate(()=>__dofTest.continueEncounter());assert((await state()).deathPending);await page.waitForTimeout(1100);assert(await page.locator('#deathConclusion').isVisible());await page.reload();assert((await state()).hp>0);assert.equal((await state()).floorNo,1);assert.equal((await boss()),null);
 console.log('PASS pending player/Boss damage reload, Reroll cost/final reservation, next-round eligibility, committed Weakness once, active HP persistence and existing ended death lifecycle');
 for(const size of [{width:320,height:568},{width:390,height:844},{width:430,height:932},{width:844,height:390}]){await page.setViewportSize(size);await prepare(1);await page.waitForTimeout(380);for(const id of ['#rerollButton','#diceDetail','#die']){const b=await page.locator(id).boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=size.width&&b.y+b.height<=size.height)}const frame=await page.locator('.encounterPanel').boundingBox();assert(frame.y>=0&&frame.y+frame.height<size.height);await page.screenshot({path:'/tmp/boss-'+size.width+'.png'})}
 assert.deepEqual(errors,[]);console.log('PASS Boss card/die/action bounds in four mobile sizes; no runtime errors');
 }finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
