const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const shell=vm.runInNewContext(sw.slice(0,sw.indexOf('self.addEventListener'))+'SHELL');
for(const file of shell)assert(fs.existsSync(path.join(root,file)),file);for(const [,file] of html.matchAll(/(?:url\(['"]?|href=['"])(\.\/assets\/[^)'"\s]+)/g))assert(fs.existsSync(path.join(root,file)),file);
assert(!/\.\/icons\/|\.\/assets\/card_|\.\/card_frame\.png/.test(html+sw+fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8')));assert.equal(shell.filter(s=>s.startsWith('./assets/cards/')).length,25);
const server=http.createServer((q,r)=>fs.readFile(path.join(root,new URL(q.url,'http://localhost').pathname==='/'?'index.html':new URL(q.url,'http://localhost').pathname),(err,data)=>{r.setHeader('Content-Type',q.url.endsWith('.webp')?'image/webp':q.url.endsWith('.js')?'application/javascript':q.url.endsWith('.webmanifest')?'application/manifest+json':'text/html');r.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.PWA_BROWSER});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404)missing.push(r.url())});const url='http://127.0.0.1:'+server.address().port;await page.goto(url);
 async function image(panel,file){const selector=panel+' .cardImage';await page.waitForFunction(selector=>{const e=document.querySelector(selector);return e&&e.complete&&e.naturalWidth>0&&e.closest('.cardArtwork').classList.contains('hasCardImage')},selector);assert((await page.locator(selector).getAttribute('src')).endsWith(file));assert.equal(await page.locator(selector).evaluate(e=>getComputedStyle(e).objectFit),'cover');const bounds=await page.locator(selector).boundingBox();assert(bounds.width>80&&bounds.height>20)}
 for(const [kind,file] of [['basic','guardian.webp'],['wretch','wretch.webp'],['spirit','spirit.webp'],['mimic','mimic.webp']]){await page.evaluate(kind=>{const t=__dofTest;t.newRun();if(kind==='mimic')t.setRoomFixture(t.state().currentId,{chest:{kind:'mimic',opened:true,cardSeen:true,itemId:null,fallbackItemId:null}});t.showDice('monster',kind==='mimic'?'basic':kind)},kind);await image('.encounterPanel',file)}
 for(const [type,file] of [['spikes','spikes.webp'],['trap','darts.webp'],['heal','shrine.webp']]){await page.evaluate(type=>{const t=__dofTest;t.newRun();t.setRoomFixture(t.state().currentId,{event:type,scavenged:false});t.showDice(type)},type);await image('.encounterPanel',file)}
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setRoomFixture(t.state().currentId,{scavenged:true});t.showDice('trap')});await image('.encounterPanel','scavenge-trap.webp');
 for(const [type,file] of [['garden','garden.webp'],['flower','flower.webp']]){await page.evaluate(type=>{const t=__dofTest;t.newRun();t.setRoomFixture(t.state().currentId,{event:type,contentState:{seen:false,resolved:false,consumed:false}});t.openContent(t.state().currentId,true)},type);await image('.itemChoicePanel',file)}
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setRoomFixture(t.state().currentId,{event:'chest',chest:{kind:'consumable',itemId:'flask',opened:false,cardSeen:false,fallbackItemId:null}});t.openChestCard(t.state().currentId,false)});await image('.itemChoicePanel','chest.webp');await page.screenshot({path:'/tmp/dof-chest-art.webp'});
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setFloor(25);t.setCurrent(t.state().exitId);t.openBossCard(t.state().exitId)});await image('.itemChoicePanel','guardian.webp');await page.evaluate(()=>__dofTest.beginBossFight());await image('.encounterPanel','guardian.webp');
 await page.evaluate(()=>{__dofTest.newRun();__dofTest.showDice('monster','thief')});assert.equal(await page.locator('.encounterPanel .cardImage').count(),0);assert.equal(await page.locator('.encounterPanel #eventArt').evaluate(e=>getComputedStyle(e).visibility),'visible');
 await page.evaluate(()=>{__dofTest.newRun();__dofTest.showDice('monster','wretch');__dofTest.revealOutcome();__dofTest.saveRun()});await image('.encounterPanel','wretch.webp');const pending=await page.evaluate(()=>__dofTest.serializeRun().pending.encounter);await page.reload();await page.locator('#continueRun').click();await image('.encounterPanel','wretch.webp');assert.deepEqual(await page.evaluate(()=>__dofTest.serializeRun().pending.encounter),pending);await page.screenshot({path:'/tmp/dof-wretch-art.webp'});
 await page.evaluate(()=>{__dofTest.clearPending();__dofTest.showCodex()});assert.equal(await page.locator('.codexTile[data-entry="unknown"] img').count(),0);assert(await page.locator('.codexTile[data-entry="creature:wretch"] img').count());await page.locator('.codexTile[data-entry="creature:wretch"]').click();await image('#codexCard','wretch.webp');await page.screenshot({path:'/tmp/dof-archive-art.webp'});await page.evaluate(()=>{__dofTest.closeCodex();__dofTest.clearPending();__dofTest.newRun()});
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();if(await page.locator('#continueRun').isVisible())await page.locator('#continueRun').click();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.context().setOffline(true);await page.goto(url);if(await page.locator('#continueRun').isVisible())await page.locator('#continueRun').click();
 await page.evaluate(()=>{__dofTest.showDice('monster','wretch')});await image('.encounterPanel','wretch.webp');assert(await page.evaluate(()=>caches.has('dungeon-of-fate-v2.23.3-1')));assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);
 console.log('PASS all moved UI/icon/CSS/manifest/shell paths; all 25 supplied images decoded and clipped; boss placeholder, icon fallback, unknown concealment, Archive details, pending reload and actual offline art; no 404s/runtime errors');
 }finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
