const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>{res.setHeader('Content-Type',req.url.endsWith('.png')?'image/png':req.url.endsWith('.js')?'application/javascript':'text/html');res.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const codex=()=>page.evaluate(()=>__dofTest.codex()),state=()=>page.evaluate(()=>__dofTest.state()),save=()=>page.evaluate(()=>{const s=__dofTest.serializeRun();delete s.savedAt;return s});
 let c=await codex();assert.equal(Object.keys(c.entries).length,15);assert.equal(Object.keys(c.discovered).length,1);const initial=c.discovered;
 await page.evaluate(()=>{for(let i=0;i<10;i++)__dofTest.newFloor()});assert.deepEqual((await codex()).discovered,initial);
 await page.evaluate(()=>__dofTest.showCodex());assert.equal(await page.locator('.codexTile:disabled').count(),14);assert.equal(await page.locator('.codexTile:disabled').first().innerText(),'?\n???');assert.equal(await page.evaluate(()=>__dofTest.openCodexDetail('creature:mimic')),false);
 const before=await save();await page.locator('.codexTile:not(:disabled)').click();await page.locator('#codexName').tap();assert(await page.locator('#codexDetail').isVisible());assert.equal(await page.locator('#codexCard button:visible').count(),0);await page.locator('#codexDetail').tap({position:{x:4,y:4}});assert(!await page.locator('#codexDetail').isVisible());assert.deepEqual(await save(),before);await page.keyboard.press('Escape');
 await page.evaluate(()=>{__dofTest.acquireTrinket('doll')});await page.waitForSelector('#itemChoice:not([hidden])');assert((await codex()).discovered['trinket:doll']);assert.equal(await page.locator('.itemChoicePanel button:visible').count(),0);await page.locator('#itemName').tap();assert(await page.locator('#itemChoice').isVisible());await page.locator('#itemChoice').tap({position:{x:4,y:4}});assert(!await page.locator('#itemChoice').isVisible());
 for(const id of ['eye','blood'])await page.evaluate(id=>{__dofTest.acquireTrinket(id);__dofTest.closeItemCard()},id);
 await page.evaluate(()=>__dofTest.acquireTrinket('horseshoe'));await page.waitForSelector('#replaceSelected:visible');assert.equal(await page.locator('.itemChoicePanel button:visible').count(),1);await page.locator('.replaceTrinket[data-item="eye"]').click();assert((await state()).relics.trinkets.includes('eye'));await page.locator('#replaceSelected').click();assert((await state()).relics.trinkets.includes('horseshoe'));
 for(const [type,kind,id] of [['monster','basic','creature:basic'],['monster','thief','creature:thief'],['monster','spirit','creature:spirit'],['trap','basic','hazard:trap'],['heal','basic','discovery:shrine']]){await page.evaluate(({type,kind})=>{__dofTest.newRun();__dofTest.setCombo(5);__dofTest.showDice(type,kind);__dofTest.revealOutcome()},{type,kind});assert((await codex()).discovered[id]);await page.waitForTimeout(600);const pending=(await save()).pending;await page.locator('#diceResult').tap();assert.deepEqual((await save()).pending,pending);assert.equal(await page.locator('.encounterPanel button:visible').count(),1);await page.locator('#rerollButton').tap();assert.deepEqual((await save()).pending,pending);await page.locator('#diceOverlay').tap({position:{x:4,y:4}});assert.equal((await save()).pending.encounter,null)}
 const learned=(await codex()).discovered;await page.evaluate(()=>{__dofTest.newRun();__dofTest.setVitals(1,false);__dofTest.resolveDice('trap',1)});await page.waitForTimeout(1200);for(const id of Object.keys(learned))assert((await codex()).discovered[id]);await page.reload();for(const id of Object.keys(learned))assert((await codex()).discovered[id]);
 for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.evaluate(()=>{__dofTest.newRun();__dofTest.inspectItem('consumable',__dofTest.state().relics.consumable)});await page.waitForTimeout(100);const b=await page.locator('.itemChoicePanel').boundingBox();assert(b.x>0&&b.y>=0&&b.x+b.width<size.width&&b.y+b.height<size.height);assert(await page.locator('.itemChoicePanel').evaluate(e=>getComputedStyle(e,'::after').backgroundImage.includes('card_outer_frame.png')));assert.equal(await page.locator('.itemChoicePanel button:visible').count(),0);await page.locator('#itemChoice').tap({position:{x:4,y:4}});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>__dofTest.showCodex());await page.screenshot({path:'/tmp/dof-codex.png'});// Storage failure and corrupt metadata must not break the active run.
 await page.evaluate(()=>{__dofTest.closeCodex();window.realSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='dof.codex')throw Error('quota');return realSet.call(this,k,v)};__dofTest.newRun();__dofTest.offerConsumable('flask')});assert((await codex()).discovered['consumable:flask']);await page.evaluate(()=>{Storage.prototype.setItem=realSet;localStorage.setItem('dof.codex','{bad');});await page.reload();assert(await page.locator('#continueRun').isVisible());await page.locator('#continueRun').click();assert((await state()).hp>0);assert.deepEqual(errors,[]);console.log('PASS 15-entry registry, generation privacy, real discovery, unknown/detail input, one action, replacements, backdrop acceptance, death/new-run/reload meta persistence, frame/mobile bounds');
 }finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
