const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'application/javascript':'text/html');res.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const save=()=>page.evaluate(()=>__dofTest.serializeRun()),state=()=>page.evaluate(()=>__dofTest.state()),resume=async()=>{await page.reload();await page.locator('#continueRun').click()};
 const stats=await page.evaluate(()=>{const t=__dofTest,rng=Math.random;let eligible=0,spawn=0,loot={consumable:0,trinket:0,mimic:0};for(let seed=1;seed<=1500;seed++){let n=seed;Math.random=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296};t.setFloor(1+seed%24);const s=t.serializeRun(),found=s.floor.rooms.filter(r=>r.chest);if(found.length>1)throw Error('max one');if(found.length||t.chestCandidates().length)eligible++;if(!t.validateSave(s))throw Error('invalid generated save');if(found.length){spawn++;const r=found[0];loot[r.chest.kind]++;if(r.links.length!==1||r.id===s.floor.startId||r.id===s.floor.exitId||s.fateGate?.branchIds.includes(r.id))throw Error('placement');const seen=new Set([s.floor.startId]),q=[s.floor.startId];for(let i=0;i<q.length;i++)for(const id of s.floor.rooms[q[i]].links)if(id!==r.id&&!seen.has(id)){seen.add(id);q.push(id)}if(!seen.has(s.floor.exitId))throw Error('exit blocked');const before=JSON.stringify(s.floor.rooms);t.generateChest();if(JSON.stringify(t.serializeRun().floor.rooms)!==before)throw Error('second chest')}
 }Math.random=rng;const weights={consumable:0,trinket:0,mimic:0};for(let i=0;i<10000;i++)weights[t.chooseChestContent((i+.5)/10000).kind]++;return{eligible,spawn,loot,weights}});assert(stats.spawn/stats.eligible>.26&&stats.spawn/stats.eligible<.34);assert.deepEqual(stats.weights,{consumable:4500,trinket:3500,mimic:2000});console.log('PASS optional terminal placement, max one, exit, generation/save validation',stats);
 async function fixture(kind,item='flask',bargain=false){return page.evaluate(({kind,item,bargain})=>{const t=__dofTest;t.newRun();for(let i=0;i<200;i++){t.setFloor(5);let s=t.serializeRun(),r=s.floor.rooms.find(r=>r.chest);if(!r)continue;r.chest={kind,itemId:kind==='mimic'?null:item,fallbackItemId:kind==='trinket'?'ward':null,opened:false,cardSeen:false};const parent=r.links[0];s.floor.currentId=parent;s.floor.rooms[parent].known=true;s.floor.rooms[parent].visited=true;s.floor.rooms[parent].searched=true;s.floor.rooms[parent].eventResolved=true;s.run.searched[parent]=true;s.floor.history.push(parent);s.run.combo=5;s.run.hp=1;if(bargain)s.relicState.bargainCharges=1;if(!t.restoreRun(s))throw Error('fixture');t.saveRun();window.chestId=r.id;t.enter(r.id);return r.id}throw Error('no chest')},{kind,item,bargain})}
 let id=await fixture('consumable');assert.equal(await page.locator('#itemName').innerText(),'Treasure Chest');assert(!(await save()).floor.rooms[id].chest.opened);await page.locator('#itemName').tap();await resume();assert((await save()).floor.rooms[id].chest.cardSeen);assert(!(await save()).floor.rooms[id].chest.opened);assert.equal((await state()).cards.active,null);
 const parent=(await save()).floor.rooms[id].links[0];await page.evaluate(parent=>{const t=__dofTest;t.enter(parent)},parent);await page.evaluate(id=>__dofTest.enter(id),id);assert.equal((await state()).cards.active,null);await page.locator('.current').tap();assert.equal((await state()).cards.active.type,'chest');
 const gold=(await state()).gold;await page.locator('#chestOpen').tap();assert((await save()).floor.rooms[id].chest.opened);assert.equal(await page.locator('#acquisitionReveal').count(),1);await resume();assert.equal((await state()).cards.active.id,'flask');assert.equal((await state()).cards.active.decision,true);await page.locator('#takeItem').click();await resume();assert.equal((await state()).relics.consumable,'flask');assert.equal((await state()).gold,gold);assert.equal(await page.evaluate(id=>__dofTest.openChestCard(id),id),false);assert.equal(await page.locator('.chestOpened').count(),1);
 console.log('PASS first-show/dismiss/revisit/reopen, fixed contents, source reveal, Consumable choice and single reward');
 id=await fixture('trinket','horseshoe');await page.evaluate(()=>{const t=__dofTest;t.closeItemCard();for(const item of ['doll','blood','eye']){t.acquireTrinket(item);t.closeItemCard()}t.openChestCard(t.state().currentId)});await page.locator('#chestOpen').click();await resume();assert.equal((await state()).cards.active.decision,true);assert.equal((await state()).relics.trinkets.length,3);await page.locator('.replaceTrinket[data-item="eye"]').click();await resume();assert.deepEqual((await state()).relics.trinkets,['doll','blood','horseshoe']);assert((await save()).floor.rooms[id].chest.opened);
 id=await fixture('trinket','doll');await page.evaluate(()=>{const t=__dofTest;t.closeItemCard();t.acquireTrinket('doll');t.closeItemCard();t.openChestCard(t.state().currentId);t.openChest()});await resume();assert.equal((await state()).cards.active.id,'ward');assert.equal((await state()).relics.trinkets.filter(x=>x==='doll').length,1);
 console.log('PASS fourth-Trinket replacement and predetermined duplicate fallback');
 id=await fixture('mimic');await page.evaluate(()=>{window.rng=Math.random;Math.random=()=>0});await page.locator('#chestOpen').click();await page.evaluate(()=>Math.random=rng);let first=await save();assert.equal(first.pending.encounter.type,'monster');assert.equal(first.pending.encounter.monsterKind,'basic');assert.equal(first.pending.encounter.roll,1);assert.equal(await page.locator('#diceTitle').innerText(),'MIMIC');await resume();assert.deepEqual((await save()).pending.encounter,first.pending.encounter);await page.evaluate(()=>__dofTest.revealOutcome());await page.waitForTimeout(400);assert.equal((await state()).hp,1);const b=await page.locator('#rerollButton').boundingBox();await page.evaluate(()=>{window.rng=Math.random;Math.random=()=>.999});await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForTimeout(700);await page.mouse.up();await page.evaluate(()=>Math.random=rng);assert.equal((await save()).pending.encounter.roll,6);assert.equal((await state()).combo,4);await resume();await page.waitForFunction(()=>__dofTest.serializeRun().pending.encounter?.phase==='preview');assert.equal(await page.locator('#diceTitle').innerText(),'MIMIC');await page.locator('#diceResult').tap();const done=await save();await resume();assert.deepEqual((await save()).run,done.run);assert((await save()).floor.rooms[id].chest.opened);assert.equal((await save()).pending.encounter,null);
 console.log('PASS Mimic uses normal reserved Monster result, hold reroll, final acceptance and no reopening');
 await fixture('mimic',null,true);assert.equal((await save()).relicState.bargainCharges,0);assert.equal((await save()).relicState.bargainRoom,(await save()).floor.currentId);await page.evaluate(()=>{const t=__dofTest;t.openChest();t.resolveDice('monster',1);t.continueEncounter()});assert.equal((await state()).hp,1);assert.equal((await state()).deathPending,false);assert.equal((await save()).relicState.bargainRoom,null);
 console.log('PASS last-entry Bargain protection survives the Chest decision into Mimic combat');

 // No eligible empty terminal: generator must do nothing, not distort topology or specials.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();for(const r of t.state().rooms)if(r.active&&r.event==='empty')t.setRoomFixture(r.id,{event:'treasure'});const before=JSON.stringify(t.serializeRun().floor);t.generateChest();if(JSON.stringify(t.serializeRun().floor)!==before)throw Error('forced placement')});
 // Existing saves without any chest fields remain compatible. Invalid content cannot load.
 const old=await save();for(const r of old.floor.rooms){if(r.event==='chest'){r.event='empty';r.hint='neutral'}delete r.chest}old.gameVersion='2.17.1';assert(await page.evaluate(s=>__dofTest.validateSave(s),old));id=await fixture('consumable');const bad=await save();bad.floor.rooms[id].chest.itemId='fake';assert.equal(await page.evaluate(s=>__dofTest.validateSave(s),bad),false);
 for(const size of [{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(size);const b=await page.locator('#chestOpen').boundingBox();assert(b.y>=0&&b.y+b.height<=size.height);assert(b.width>=44&&b.height>=44)}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/dof-chest.png'});assert.deepEqual(errors,[]);console.log('PASS no-eligible fallback, compatibility, invalid loot validation, phone card bounds, no runtime errors');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
