const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>{res.setHeader('Content-Type',req.url.endsWith('.png')?'image/png':req.url.endsWith('.js')?'application/javascript':'text/html');res.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.PWA_BROWSER});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 await context.addInitScript(()=>{const original=window.setTimeout,clear=window.clearTimeout;let id=-1;window.hops=new Map();window.setTimeout=function(fn,ms,...args){if(fn.name==='hop'){const k=id--;hops.set(k,{fn,ms});return k}return original(fn,ms,...args)};window.clearTimeout=function(k){if(hops.has(k))hops.delete(k);else clear(k)};window.hop=()=>{const [k,v]=hops.entries().next().value;hops.delete(k);v.fn();return v.ms}});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const snap=()=>page.evaluate(()=>__dofTest.serializeRun()),state=()=>page.evaluate(()=>__dofTest.state());
 async function resume(){await page.reload();await page.locator('#continueRun').click()}
 async function fixture(type){await page.evaluate(type=>{const t=__dofTest;t.newRun();t.setRoomFixture(t.state().currentId,{event:type,contentState:{seen:false,resolved:false,consumed:false}});t.setCombo(5)},type)}
 async function roll(type,n){await fixture(type);await page.evaluate(({type,n})=>{const random=Math.random;Math.random=()=>((n-.5)/6);__dofTest.showDice(type);Math.random=random;__dofTest.revealOutcome()},{type,n})}
 async function accept(){await page.locator('#diceOverlay').tap({position:{x:4,y:4}})}
 // Original/result/final/condition state is durable for every new explicit encounter.
 for(const type of ['spikes','mosquitoes','spores','stones','corpse','hole']){
  await roll(type,1);let s=await snap();assert.deepEqual(s.run.conditions,{});assert.equal(s.run.hp,3);assert.equal(s.run.combo,5);assert(await page.evaluate(()=>__dofTest.validateSave(__dofTest.serializeRun())));await resume();assert.deepEqual((await snap()).pending.encounter,s.pending.encounter);assert.deepEqual((await snap()).run,s.run);await page.waitForSelector('#rerollButton:not([hidden])');
  await page.evaluate(()=>{const random=Math.random;Math.random=()=>.99;__dofTest.rerollOutcome();Math.random=random});s=await snap();assert.equal(s.run.combo,4);assert.equal(s.pending.encounter.roll,6);assert(s.pending.encounter.rerollUsed);await resume();assert.equal((await snap()).pending.encounter.roll,6);assert.equal((await snap()).run.combo,4);await page.evaluate(()=>__dofTest.revealOutcome());assert(await page.locator('#rerollButton').isHidden());await accept();assert.equal((await snap()).pending.encounter,null);assert.deepEqual((await snap()).run.conditions,{});assert.equal((await snap()).run.hp,3);await resume();assert.equal((await snap()).pending.encounter,null);
 }
 assert(!(await page.evaluate(()=>__dofTest.codex())).discovered['hazard:wasps']);
 console.log('PASS six new dice paths: pending original reload, cost/final reservation, rejected consequences, no extra reroll');
 for(const type of ['spikes','mosquitoes','spores','stones']){await roll(type,6);await page.waitForSelector('#rerollButton:not([hidden])');await page.evaluate(()=>{const random=Math.random;Math.random=()=>0;__dofTest.rerollOutcome();Math.random=random});await resume();await page.evaluate(()=>__dofTest.revealOutcome());const expected=(await snap()).pending.encounter.preview.after;await accept();assert.deepEqual((await snap()).run.conditions,expected.conditions);assert.equal((await snap()).run.hp,expected.hp);await resume();assert.deepEqual((await snap()).run.conditions,expected.conditions);assert.equal((await snap()).run.hp,expected.hp)}
 // Lethal Sickness preview must itself be a valid resumable state, even at one Heart.
 await roll('spikes',1);await page.evaluate(()=>{const t=__dofTest,s=t.serializeRun();s.run.hp=1;s.run.conditions={sickness:5};s.pending.encounter.phase='ready';t.restoreRun(s);t.revealOutcome()});assert.equal((await snap()).pending.encounter.preview.after.hp,0);assert(await page.evaluate(()=>__dofTest.validateSave(__dofTest.serializeRun())));await resume();await accept();await page.waitForFunction(()=>__dofTest.state().gameOver);assert.equal((await state()).hp,0);assert.equal((await snap()).run.conditions.sickness,undefined);
 // Ward still permits first discovery and visible presentation, but no die or consequences.
 await fixture('spikes');await page.evaluate(()=>{const c=JSON.parse(localStorage.getItem('dof.codex'));delete c.discovered['hazard:spikes'];localStorage.setItem('dof.codex',JSON.stringify(c));__dofTest.saveRun()});await resume();assert(!(await page.evaluate(()=>__dofTest.codex())).discovered['hazard:spikes']);await page.evaluate(()=>{__dofTest.setConsumable('ward');__dofTest.useConsumable(true);__dofTest.showDice('spikes')});assert.equal((await snap()).pending.encounter,null);assert.equal((await state()).relics.wardArmed,false);assert.equal(await page.locator('#itemName').innerText(),'Spikes');assert.match(await page.locator('#itemVisual').innerText(),/DISARMED/);assert((await page.evaluate(()=>__dofTest.codex())).discovered['hazard:spikes']);await resume();assert.equal(await page.locator('#itemName').innerText(),'Spikes');assert.deepEqual((await snap()).run.conditions,{});await page.locator('#itemChoice').tap({position:{x:4,y:4}});
 for(const type of ['mosquitoes','spores','stones']){await fixture(type);await page.evaluate(type=>{__dofTest.setConsumable('ward');__dofTest.useConsumable(true);__dofTest.showDice(type);__dofTest.revealOutcome()},type);assert((await state()).relics.wardArmed);assert((await snap()).pending.encounter)}
 // Preview and commit all six faces including pending supplies replacement and Wasps chain.
 for(const type of ['corpse','hole'])for(let n=1;n<=6;n++){
  await roll(type,n);const s=await snap();await accept();let a=await snap();const r=a.floor.rooms[a.floor.currentId];assert(r.contentState.resolved);assert.equal(a.run.hp,3);assert.deepEqual(a.run.conditions,{});
  assert.equal(a.run.gold,s.pending.encounter.preview.after.gold);assert.equal(a.run.combo,s.pending.encounter.preview.after.combo);
  if(type==='corpse'&&n>=5){assert.equal(a.pending.cards.active.id,s.pending.encounter.rewardItem);await resume();assert.equal((await snap()).pending.cards.active.id,s.pending.encounter.rewardItem);await page.evaluate(()=>__dofTest.closeItemCard())}
  if(type==='hole'&&n<=2){assert.equal(await page.locator('#itemName').innerText(),'Wasps');assert((await page.evaluate(()=>__dofTest.codex())).discovered['hazard:wasps']);await resume();assert.equal(await page.locator('#itemName').innerText(),'Wasps');await page.locator('#itemChoice').tap({position:{x:4,y:4}})}
  await page.evaluate(()=>__dofTest.openContent(__dofTest.state().currentId,false));assert(await page.locator('#contentAction').isHidden());assert.equal(await page.evaluate(()=>__dofTest.actOnContent()),false);
 }
 console.log('PASS Ward semantic scope, discover/present/disarm, 12 Corpse/Hole outcomes, Wasps chain, reserved supplies/replacement, no farming');
 // First visit, declining and revisits use the existing card interaction philosophy.
 for(const type of ['garden','food','corpse','flower','picture','monolith','hole']){
  await fixture(type);await page.evaluate(()=>__dofTest.openContent(__dofTest.state().currentId,true));assert.equal(await page.locator('#itemName').innerText(),(await page.evaluate(type=>__dofTest.content[type].name,type)));assert((await snap()).floor.rooms[(await snap()).floor.currentId].contentState.seen);await page.locator('#itemName').tap();assert(await page.locator('#itemChoice').isVisible());await page.locator('#itemChoice').tap({position:{x:4,y:4}});assert.equal(await page.evaluate(()=>__dofTest.openContent(__dofTest.state().currentId,true)),false);await resume();await page.locator('.cell.current').tap();assert(await page.locator('#itemChoice').isVisible());assert.equal(await page.locator('.itemChoicePanel button:visible').count(),['picture','monolith'].includes(type)?0:1);
 }
 await fixture('food');await page.evaluate(()=>{__dofTest.setVitals(1,false);__dofTest.applyCondition('sickness');__dofTest.openContent(__dofTest.state().currentId,true);__dofTest.actOnContent()});assert.equal((await snap()).run.hp,1);assert.deepEqual((await snap()).run.conditions,{});assert((await snap()).floor.rooms[(await snap()).floor.currentId].contentState.consumed);
 await fixture('food');await page.evaluate(()=>{__dofTest.setVitals(2,false);__dofTest.openContent(__dofTest.state().currentId,true);__dofTest.actOnContent()});assert.equal((await snap()).run.hp,3);
 await fixture('food');await page.evaluate(()=>__dofTest.openContent(__dofTest.state().currentId,true));assert(await page.locator('#contentAction').isDisabled());assert.equal(await page.evaluate(()=>__dofTest.actOnContent()),false);assert(!(await snap()).floor.rooms[(await snap()).floor.currentId].contentState.consumed);
 await fixture('flower');const pre=(await snap()).run.combo;await page.evaluate(()=>{__dofTest.openContent(__dofTest.state().currentId,true);__dofTest.actOnContent()});assert.equal((await snap()).run.combo,Math.floor((pre+.5/(1+((pre-1)/5)**2))*100)/100);
 await fixture('garden');for(let i=0;i<2;i++){await page.evaluate(()=>{__dofTest.setVitals(1,false);for(const c of ['slowed','sickness','amnesia'])__dofTest.applyCondition(c);__dofTest.openContent(__dofTest.state().currentId,false);__dofTest.actOnContent()});assert.deepEqual((await snap()).run.conditions,{});assert.equal((await snap()).run.hp,1)}
 console.log('PASS first-show/decline/current-room reopen, informational zero-action cards, Food priority/no waste, Flower diminishing gain, reusable Garden');
 // Movement fixtures: safe visited path, manual revisit/new entry, slowed per-hop and durable counters.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state(),ids=[s.currentId];while(ids.length<6){const next=s.rooms[ids.at(-1)].links.find(id=>!ids.includes(id)&&id!==s.exitId);if(next===undefined)break;ids.push(next)}window.route=ids;for(const id of ids)t.setRoomFixture(id,{event:'empty',eventResolved:true});t.markVisited(ids);t.applyCondition('slowed');t.applyCondition('sickness');t.applyCondition('amnesia');t.saveRun();t.update()});
 let before=await snap();assert((await page.locator('.cell').count())<before.floor.rooms.filter(r=>r.known).length||before.floor.rooms.filter(r=>r.known).length<=3);const route=await page.evaluate(()=>route);assert(route.length>=2);await page.evaluate(id=>__dofTest.enter(id),route[1]);assert.equal((await snap()).run.conditions.slowed,4);assert((await snap()).run.rememberedRooms[route[1]]);assert.equal(await page.locator('#board').evaluate(e=>e.style.getPropertyValue('--arrival-ms')),'504ms');await resume();assert.equal((await snap()).run.conditions.slowed,4);assert.equal((await snap()).floor.currentId,route[1]);await page.evaluate(id=>__dofTest.travel(id),route[0]);assert.equal(await page.evaluate(()=>hop()),270);assert.equal((await snap()).run.conditions.slowed,3);await resume();assert.equal((await snap()).run.conditions.slowed,3);assert.equal((await state()).fastTraveling,false);
 await page.evaluate(()=>{__dofTest.setFloor(12);for(let i=0;i<100&&__dofTest.layerInfo().layers.length<2;i++)__dofTest.newFloor();const stairs=__dofTest.state().rooms.find(r=>r.active&&r.stairTo!==undefined);__dofTest.setCurrent(stairs.id);for(const c of ['slowed','sickness','amnesia'])__dofTest.applyCondition(c);__dofTest.traverseStairs()});assert.equal((await snap()).run.conditions.amnesia,4);await resume();assert.equal((await snap()).run.conditions.amnesia,4);
 await page.evaluate(()=>{__dofTest.setCurrent(__dofTest.state().exitId);__dofTest.markVisited([__dofTest.state().exitId]);__dofTest.descend()});assert.equal((await snap()).run.conditions.amnesia,4);assert((await snap()).run.rememberedRooms[(await snap()).floor.currentId]);await resume();assert.equal((await snap()).run.conditions.amnesia,4);
 console.log('PASS manual/revisited movement, Slowed 504ms arrival/270ms hop, per-hop safe checkpoint, memory, stairs, floor descent and reload');
 await fixture('picture');await page.evaluate(()=>{__dofTest.applyCondition('sickness');__dofTest.openContent(__dofTest.state().currentId,true)});await page.waitForTimeout(300);assert.equal((await snap()).run.conditions.sickness,5);await page.locator('#itemChoice').tap({position:{x:4,y:4}});await page.evaluate(()=>__dofTest.showCodex());await page.waitForTimeout(100);assert.equal((await snap()).run.conditions.sickness,5);await page.evaluate(()=>__dofTest.closeCodex());
 // Five completed hops expire all conditions and restore remembered presentation.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();let s=t.state(),q=[[s.currentId]],seen=new Set([s.currentId]),route=null;while(q.length){const p=q.shift();if(p.length>=6){route=p;break}for(const id of s.rooms[p.at(-1)].links)if(!seen.has(id)){seen.add(id);q.push(p.concat(id))}}if(!route)throw Error('Need six-room route');window.expiryRoute=route;for(const id of route)t.setRoomFixture(id,{event:'empty',eventResolved:true});t.markVisited(route);for(const c of ['slowed','sickness','amnesia'])t.applyCondition(c);t.travel(route.at(-1))});
 const moves=(await snap()).run.totalMoves;for(let i=1;i<=5;i++){assert.equal(await page.evaluate(()=>hop()),270);const s=await snap();assert.equal(s.run.totalMoves,moves+i);assert.equal(s.floor.currentId,(await page.evaluate(()=>expiryRoute))[i]);assert.equal(s.run.conditions.slowed,i<5?5-i:undefined);assert(await page.evaluate(()=>__dofTest.validateSave(__dofTest.serializeRun())))}assert.deepEqual((await snap()).run.conditions,{});await resume();assert.deepEqual((await snap()).run.conditions,{});
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state(),id=s.rooms[s.currentId].links[0];t.setRoomFixture(id,{event:'empty',eventResolved:false,visited:false,searched:false});t.setConsumable('coin');t.useConsumable(true);t.applyCondition('sickness');t.enter(id)});assert.equal((await snap()).run.conditions.sickness,4);assert.equal((await snap()).relicState.coinCharges,4);await resume();assert.equal((await snap()).run.conditions.sickness,4);
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setFloor(12);for(let i=0;i<100&&t.layerInfo().layers.length<2;i++)t.newFloor();t.setCurrent(t.state().rooms.find(r=>r.stairTo!==undefined).id);t.applyCondition('amnesia');for(let i=0;i<5;i++)if(!t.traverseStairs())throw Error('stairs blocked');});assert.deepEqual((await snap()).run.conditions,{});await page.emulateMedia({reducedMotion:'no-preference'});
 console.log('PASS fifth-hop expiry, new-entry Coin/counter consistency, five reciprocal stair movements');
 // Actual card geometry in supported small portrait/landscape viewports.
 for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await roll('spores',1);await page.waitForTimeout(600);const die=await page.locator('#die').boundingBox(),button=await page.locator('#rerollButton').boundingBox();assert(die.width>=70);assert(button.y+button.height<=size.height);await fixture('garden');await page.evaluate(()=>__dofTest.openContent(__dofTest.state().currentId,true));const b=await page.locator('#contentAction').boundingBox();const card=await page.locator('.itemChoicePanel').boundingBox();assert(b.y>=card.y+card.height*.65&&b.y+b.height<=card.y+card.height);assert(b.y>=0&&b.y+b.height<=size.height);assert.equal(await page.locator('.itemChoicePanel button:visible').count(),1);await page.screenshot({path:'/tmp/v221-garden-'+size.width+'.png'})}
 assert.deepEqual(errors,[]);console.log('PASS mobile dice/action bounds and no runtime errors');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
