const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>res.writeHead(err?404:200).end(data)));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);const state=()=>page.evaluate(()=>__dofTest.state());
 const stats=await page.evaluate(()=>{const t=__dofTest,check=(v,m)=>{if(!v)throw Error(m)},rng=Math.random;let gates=0,leads=0,routeLeads=0,risk=0,opportunities=0,eligible=0;const sizes={1:0,2:0,3:0},requested={1:0,2:0,3:0},bands=[0,0,0,0,0,0];
  for(let seed=1;seed<=1000;seed++){let n=seed;Math.random=()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);t.setCombo(4);t.setFloor(3+seed%18);const s=t.state(),g=s.fateGate,active=s.rooms.filter(r=>r.active);check(t.normalReachableWithoutGate(),'normal paths');
   const passive=active.filter(r=>r.scavengeOpportunity?.passiveLead);check(passive.length<=1,'passive cap');leads+=passive.length;
   for(const r of active){for(const id of r.links){check(s.rooms[id].active&&s.rooms[id].links.includes(r.id),'reciprocal');check(Math.abs(r.id%9-id%9)+Math.abs(Math.floor(r.id/9)-Math.floor(id/9))===1,'grid corridor')}if(r.id!==s.exitId){opportunities++;const o=r.scavengeOpportunity;check(o&&!o.resolved&&!r.attentionActive,'preexisting hidden fact');if(o.roll>=.75)eligible++;bands[o.roll<.45?0:o.roll<.75?1:o.roll<.85?2:o.roll<.91?3:o.roll<.95?4:5]++}}
   const prev={},q=[s.startId],seen=new Set(q);for(let i=0;i<q.length;i++)for(const id of s.rooms[q[i]].links.concat(s.rooms[q[i]].stairTo===undefined?[]:[s.rooms[q[i]].stairTo]))if(!seen.has(id)&&(!g||!g.branchIds.includes(id))){seen.add(id);prev[id]=q[i];q.push(id)}let at=s.exitId,route=[];while(at!==undefined){route.push(at);at=prev[at]}if(passive.some(r=>route.includes(r.id)))routeLeads++;
   if(g){gates++;sizes[g.branchIds.length]++;requested[g.requestedSize]++;check(g.branchIds.length>=1&&g.branchIds.length<=3&&new Set(g.branchIds).size===g.branchIds.length,'size');check(g.branchIds.every(id=>!s.rooms[id].known),'fog');check(g.branchIds.includes(g.rewardRoomId)&&s.rooms[g.rewardRoomId].event===g.reward,'guarantee');const external=g.branchIds.flatMap(id=>s.rooms[id].links.filter(n=>!g.branchIds.includes(n)).map(n=>[id,n]));check(external.length===1&&external[0][0]===g.roomId&&external[0][1]===g.parentId,'single gate connection');for(const id of g.branchIds)if(id!==g.rewardRoomId){check(['empty','monster','trap'].includes(s.rooms[id].event),'one premium opportunity');if(s.rooms[id].event!=='empty')risk++}}
  }
  Math.random=rng;check(leads>590&&leads<710,'lead chance');check(routeLeads>100,'exit route exposure');check(eligible/opportunities>.23&&eligible/opportunities<.27,'existing meaningful bands');check(risk>0&&sizes[1]&&sizes[2]&&sizes[3],'variety');return{floors:1000,gates,sizes,requested,leads,routeLeads,opportunities,bands,risk};
 });console.log('PASS finite opportunity/exposure and branch generation',stats);
 // Find a real 3-room branch and retain unknown interior behind its frontier gate.
 const g=await page.evaluate(()=>{const t=__dofTest;t.newRun();for(let i=0;i<200;i++){t.setFloor(6);const s=t.state();if(s.fateGate?.branchIds.length===3){const g=s.fateGate;t.setRoomFixture(g.parentId,{visited:true,searched:true,eventResolved:true,event:'empty'});t.setCurrent(g.parentId);t.markVisited([g.parentId]);g.branchIds.forEach(id=>t.setRoomFixture(id,{event:'empty'}));return g}}throw Error('branch not found')});
 let s=await state();assert(s.rooms[g.roomId].known);assert(g.branchIds.filter(id=>id!==g.roomId).every(id=>!s.rooms[id].known));
 await page.evaluate(g=>{const t=__dofTest;t.acquireTrinket('eye');t.closeItemCard();g.branchIds.filter(id=>id!==g.roomId).forEach(id=>{t.setRoomFixture(id,{event:'monster',monsterKind:'spirit'});t.revealClue(g.parentId,id)});t.setCombo(g.requirement-.01);t.enter(g.roomId);t.travel(g.branchIds[2])},g);await page.waitForTimeout(220);s=await state();assert.equal(s.currentId,g.parentId);assert(g.branchIds.filter(id=>id!==g.roomId).every(id=>!s.rooms[id].known&&!s.rooms[id].eyeMarked));
 await page.evaluate(g=>{__dofTest.setCombo(g.requirement);__dofTest.enter(g.roomId)},g);await page.waitForFunction(()=>!__dofTest.state().pendingAction);s=await state();assert(s.fateGate.entered&&!s.fateGate.resolved);assert.equal(s.combo,g.requirement);assert(s.rooms[g.roomId].links.filter(id=>g.branchIds.includes(id)).every(id=>s.rooms[id].known&&s.rooms[id].eyeMarked));
 // Internal movement ignores FATE; returning out always works. Full primary resolution quiets gate.
 await page.evaluate(g=>{const t=__dofTest;t.setCombo(1);for(const id of g.branchIds)t.setRoomFixture(id,{event:'empty'});},g);
 for(const id of g.branchIds.filter(id=>id!==g.roomId)){await page.evaluate(({g,id})=>{const t=__dofTest,s=t.state();if(!s.rooms[s.currentId].links.includes(id))t.enter(g.roomId);t.enter(id)},{g,id});await page.waitForFunction(()=>!__dofTest.state().pendingAction)}
 s=await state();assert(s.fateGate.resolved);await page.evaluate(g=>__dofTest.travel(g.parentId),g);await page.waitForFunction(()=>!__dofTest.state().fastTraveling);assert.equal((await state()).currentId,g.parentId);await page.evaluate(g=>__dofTest.travel(g.roomId),g);assert.equal((await state()).fastTraveling,false);console.log('PASS branch fog, clue/Eye privacy, threshold, internal travel/exit safety and branch-aware resolution');
 // Clue reads an existing outcome without altering it. Marked Trap keeps normal risk.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();localStorage.setItem('dof.learnedScavenge','1');const s=t.state(),id=s.rooms[s.currentId].links[0];window.leadId=id;t.markVisited([id]);t.setRoomFixture(id,{scavengeOpportunity:{roll:.98,resolved:false,passiveLead:false}});t.revealClue(s.currentId,id,'loot')});await page.waitForTimeout(230);s=await state();const lead=await page.evaluate(()=>leadId);assert.equal(s.rooms[lead].scavengeOpportunity.roll,.98);assert(s.rooms[lead].attentionActive);assert.equal(s.gold,0);await page.evaluate(id=>{__dofTest.setCurrent(id);__dofTest.scavenge(id)},lead);s=await state();assert.equal(s.pendingAction,'trap');assert(s.rooms[lead].scavengeOpportunity.resolved&&!s.rooms[lead].attentionActive&&!s.rooms[lead].lootClued);await page.evaluate(()=>__dofTest.clearPending());
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state();for(const r of s.rooms)if(r.active)t.setRoomFixture(r.id,{scavengeOpportunity:{roll:.1,resolved:false,passiveLead:false}});window.facts=JSON.stringify(t.state().rooms.map(r=>r.scavengeOpportunity));t.revealClue(s.currentId,s.currentId,'loot')});await page.waitForTimeout(230);assert(await page.evaluate(()=>facts===JSON.stringify(__dofTest.state().rooms.map(r=>r.scavengeOpportunity))));assert((await state()).rooms.some(r=>r.clued));assert(!(await state()).rooms.some(r=>r.attentionActive));console.log('PASS Clues reveal existing risk, finite resolution and no-opportunity truthful fallback');
 // Real source → item → card timing; inspection skips it and the demo cannot use anything.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();localStorage.setItem('dof.learnedScavenge','1');t.setConsumable(null);t.setRoomFixture(t.state().currentId,{scavengeOpportunity:{roll:.93,resolved:false,passiveLead:false}});window.rng=Math.random;Math.random=()=>.99;t.scavenge(t.state().currentId);Math.random=rng});assert.equal(await page.locator('#acquisitionReveal').count(),1);assert(await page.locator('#itemChoice').isHidden());assert(await page.locator('.discoveryArt').innerText());await page.waitForTimeout(200);await page.screenshot({path:'/tmp/dof-discovery.png'});await page.waitForSelector('#itemChoice:not([hidden])');assert.equal(await page.locator('#acquisitionReveal').count(),0);const held=(await state()).relics.consumable;assert(held);assert.equal(await page.locator('#itemArt.holdDemo').count(),1);const before=(await state()).relics;await page.waitForTimeout(1700);assert.deepEqual((await state()).relics,before);await page.screenshot({path:'/tmp/dof-hold-demo.png'});await page.locator('#itemName').tap();await page.locator('#consumableSlot').tap();assert.equal(await page.locator('#acquisitionReveal').count(),0);await page.locator('#itemName').tap();
 // Check presentation at 120 ms, progress after 200 ms and unchanged 550 ms firing.
 let box=await page.locator('#consumableSlot').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(120);assert.equal(await page.locator('#consumableSlot.holding').count(),0);await page.mouse.up();assert((await state()).cards.active);await page.locator('#itemName').tap();
 box=await page.locator('#consumableSlot').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(240);assert.equal(await page.locator('#consumableSlot.holding').count(),1);assert(await page.locator('#consumableSlot').evaluate(el=>parseFloat(el.style.getPropertyValue('--charge'))>130));await page.waitForTimeout(340);assert.equal((await state()).relics.consumable,null);await page.mouse.up();
 await page.evaluate(()=>{__dofTest.newRun();localStorage.setItem('dof.learnedScavenge','1');__dofTest.setRoomFixture(__dofTest.state().currentId,{scavengeOpportunity:{roll:.1,resolved:false,passiveLead:false}})});box=await page.locator('.current').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(120);assert.equal(await page.locator('.fast-charge').count(),0);await page.mouse.up();assert(!(await state()).rooms[(await state()).currentId].scavenged);
 await page.mouse.down();await page.waitForTimeout(240);assert.equal(await page.locator('.fast-charge').count(),1);await page.waitForTimeout(110);assert((await state()).rooms[(await state()).currentId].scavenged);await page.mouse.up();console.log('PASS acquisition timing/identity, inspection, noninteractive hold demo, 200 ms visual delay and unchanged 320/550 ms holds');
 // Altar remains a readable landmark, only useful resources breathe.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state(),id=s.rooms[s.currentId].links[0];window.altarId=id;t.setRoomFixture(id,{event:'altar',known:true,searched:false,altarCardSeen:false,altarUsed:false});});assert.equal(await page.locator('.altarLandmark').count(),0);
 await page.evaluate(()=>{__dofTest.enter(altarId)});await page.waitForFunction(()=>__dofTest.state().cards.active?.type==='altar');await page.locator('#itemName').tap();assert.equal(await page.locator('.altarLandmark .icon').innerText(),'✦');assert.equal(await page.locator('.altarUseful').count(),0);await page.evaluate(()=>{__dofTest.setVitals(2,false);__dofTest.setCombo(3)});assert.equal(await page.locator('.altarUseful').count(),1);await page.screenshot({path:'/tmp/dof-altar.png'});await page.evaluate(()=>__dofTest.setCombo(1));assert.equal(await page.locator('.altarUseful').count(),0);await page.evaluate(()=>{__dofTest.setCombo(3);__dofTest.openAltar(altarId);__dofTest.sacrificeAltar()});assert.equal(await page.locator('.altarSpent').count(),1);assert.equal(await page.locator('.altarUseful').count(),0);
 for(const size of [{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(size);await page.locator('#consumableSlot').tap();const b=await page.locator('.itemChoicePanel').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=size.width&&b.y+b.height<=size.height);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight));await page.locator('#itemName').tap()}
 assert.deepEqual(errors,[]);console.log('PASS Altar landmark states, phone card bounds, no runtime errors');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
