const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>res.writeHead(err?404:200).end(data)));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const state=()=>page.evaluate(()=>__dofTest.state());
 // Generated hints are facts; unknown stays neutral. Check 300 actual floors.
 const hints=await page.evaluate(()=>{let counts={safe:0,danger:0,fortune:0,neutral:0};for(let i=0;i<300;i++){__dofTest.setFloor(1+i%20);for(const r of __dofTest.state().rooms.filter(r=>r.active)){counts[r.hint]++;const danger=['monster','trap'].includes(r.event);if(r.hint==='safe'&&danger||r.hint==='danger'&&!danger||r.hint==='fortune'&&!['treasure','rich','key','trinket','consumable'].includes(r.event))throw Error('false hint')}}return counts});assert(Object.values(hints).every(n=>n>0));console.log('PASS truthful hints',hints);
 // A deterministic visited corridor: no events may recur, no hidden shortcut.
 const corridor=()=>page.evaluate(()=>{const t=__dofTest;t.newRun();const ids=[10,11,12,13];for(const r of t.state().rooms)t.setRoomFixture(r.id,{links:[],active:ids.includes(r.id),known:ids.includes(r.id),visited:ids.includes(r.id),searched:true,eventResolved:true,event:'treasure',scavenged:false,scavengeOpportunity:{roll:.8,resolved:false,passiveLead:false}});ids.forEach((id,i)=>t.setRoomFixture(id,{links:ids.filter((_,j)=>Math.abs(i-j)===1)}));t.setCurrent(10);t.setCombo(5);t.setGold(123);return ids});
 await corridor();await page.locator('.cell[data-id="13"]').tap();assert.equal((await state()).currentId,10);
 const timed=await page.evaluate(async()=>{const t=__dofTest,seen=[],start=performance.now();let prev=t.state().currentId;t.travel(13);while(t.state().fastTraveling){await new Promise(r=>setTimeout(r,10));const s=t.state();if(s.currentId!==prev){seen.push({id:s.currentId,at:performance.now()-start});prev=s.currentId}}return{seen,s:t.state()}});assert.deepEqual(timed.seen.map(x=>x.id),[11,12,13]);assert(timed.seen.every((v,i)=>v.at-(i?timed.seen[i-1].at:0)>=130));assert.equal(timed.s.combo,5);assert.equal(timed.s.gold,123);assert.equal(timed.s.pendingAction,null);
 await page.evaluate(()=>{__dofTest.setCurrent(10);__dofTest.setRoomFixture(12,{visited:false});__dofTest.travel(13)});assert.equal((await state()).fastTraveling,false);
 console.log('PASS visited path, visible 150 ms steps, tap safety, no repeated rewards or FATE cost');
 // Real backward loot clue creates a finite marker. Walking never creates more loot.
 await corridor();await page.evaluate(()=>__dofTest.revealClue(10,12,'loot'));await page.waitForTimeout(220);assert((await state()).rooms[12].attentionActive);assert.equal(await page.locator('.cell[data-id="12"] .clueMark').innerText(),'❗');
 const known=await page.evaluate(async()=>{const t=__dofTest,start=performance.now();t.travel(13);while(t.state().fastTraveling)await new Promise(r=>setTimeout(r,10));return performance.now()-start});assert(known<850);
 await page.evaluate(()=>{__dofTest.setCurrent(12);__dofTest.scavenge(12)});assert(!(await state()).rooms[12].attentionActive);assert((await state()).rooms[12].attentionResolved);assert.equal(await page.locator('.cell[data-id="12"] .clueMark').count(),0);
 await corridor();const fresh=await page.evaluate(async()=>{const t=__dofTest,start=performance.now();t.travel(13);t.revealClue(10,12,'loot');while(t.state().fastTraveling)await new Promise(r=>setTimeout(r,10));return{ms:performance.now()-start,s:t.state()}});assert(fresh.ms>=820&&fresh.ms<1200);assert.equal(fresh.s.currentId,13);assert(fresh.s.rooms[12].attentionEmphasized);assert.equal(fresh.s.pendingAction,null);assert.equal(fresh.s.gold,123);console.log('PASS finite ❗, backward clue, resolution, new-only 400 ms emphasis and continued travel');
 // Seen Altars remain available without interrupting auto-walk; tap and hold stay distinct.
 await corridor();await page.evaluate(()=>{const t=__dofTest;t.setRoomFixture(11,{event:'altar',altarCardSeen:true,altarUsed:false,scavengeOpportunity:{roll:.1,resolved:false,passiveLead:false}});t.setVitals(1,false);t.travel(13)});await page.waitForFunction(()=>!__dofTest.state().fastTraveling);assert.equal((await state()).cards.active,null);
 await page.evaluate(()=>{__dofTest.travel(11)});await page.waitForFunction(()=>!__dofTest.state().fastTraveling);assert.equal((await state()).cards.active,null);await page.locator('.current').tap();assert.equal((await state()).cards.active.type,'altar');await page.locator('#itemName').tap();
 const altarBox=await page.locator('.current').boundingBox();await page.mouse.move(altarBox.x+altarBox.width/2,altarBox.y+altarBox.height/2);await page.mouse.down();await page.waitForTimeout(370);await page.mouse.up();assert((await state()).rooms[11].scavenged);assert.equal((await state()).cards.active,null);assert.equal((await state()).combo,5);assert.equal((await state()).hp,1);await page.locator('.current').tap();assert.equal((await state()).cards.active.type,'altar');await page.locator('#itemName').tap();console.log('PASS quiet Altar auto-walk, explicit tap reopen, current-room Scavenge hold');
 // Death is finalized only after protection and a readable beat, even on an early tap.
 for(const type of ['trap','monster']){
  await page.evaluate(type=>{const t=__dofTest;t.newRun();t.setVitals(1,false);t.showDice(type);t.resolveDice(type,1);t.continueEncounter();t.resolveDice(type,1)},type);
  let s=await state();assert.equal(s.hp,0);assert(s.deathPending&&!s.gameOver);assert.equal(s.causeOfDeath.type,type);assert.equal(s.diceOverlay,'flex');assert.equal(s.overlay,'none');
  await page.waitForTimeout(500);assert.equal((await state()).overlay,'none');await page.waitForFunction(()=>__dofTest.state().gameOver);assert.equal(await page.locator('#deathCause').innerText(),type==='trap'?'⚠ TRAP':'👹 MONSTER');assert.equal((await state()).hp,0);
  for(const size of [{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(size);const box=await page.locator('#overlay .panel').boundingBox();assert(box.y>=0&&box.y+box.height<=size.height);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight))}await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/dof-death-'+type+'.png'});
 }
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.acquireTrinket('doll');t.closeItemCard();t.setVitals(1,false);t.setCombo(1);t.resolveDice('trap',1)});let s=await state();assert.equal(s.hp,1);assert.equal(s.causeOfDeath,null);assert(!s.deathPending);assert(!s.relics.trinkets.includes('doll'));await page.waitForTimeout(1100);assert.equal((await state()).gameOver,false);
 await page.evaluate(()=>{const t=__dofTest;t.clearPending();t.setVitals(1,false);t.resolveDice('trap',1);t.newRun()});await page.waitForTimeout(1100);assert.equal((await state()).gameOver,false);assert.equal((await state()).causeOfDeath,null);console.log('PASS Trap/Monster cause, one-second beat, duplicate damage guard, Doll interception and restart timer safety');
 // Exercise the real automatic Trap roll, including its final visible die/result.
 await page.evaluate(()=>{__dofTest.newRun();__dofTest.setVitals(1,false);window.realRandom=Math.random;Math.random=()=>0;__dofTest.showDice('trap')});await page.waitForFunction(()=>__dofTest.state().deathPending);assert.equal(await page.locator('#diceResult').innerText(),'ROLLED 1');assert.match(await page.locator('#diceDetail').innerText(),/TRIGGERED/);assert.equal((await state()).overlay,'none');await page.waitForFunction(()=>__dofTest.state().gameOver);await page.evaluate(()=>Math.random=realRandom);
 // Starter cue survives a canceled hold, ends on inspection; ordinary tap never uses it.
 await page.evaluate(()=>__dofTest.newRun());const item=(await state()).relics.consumable,b=await page.locator('#consumableSlot').boundingBox();await page.mouse.move(b.x+20,b.y+20);await page.mouse.down();await page.mouse.move(b.x+50,b.y+20);await page.mouse.up();assert.equal(await page.locator('#consumableSlot.itemAttention').count(),1);await page.locator('#consumableSlot').tap();assert((await state()).relics.starterInspected);assert.equal(await page.locator('#consumableSlot.itemAttention').count(),0);assert.equal((await state()).relics.consumable,item);await page.locator('#itemName').tap();
 assert.deepEqual(errors,[]);console.log('PASS starter attention/inspection, no runtime errors');
}finally{if(browser)await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
