const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((q,r)=>fs.readFile(path.join(root,q.url==='/'?'index.html':q.url),(err,data)=>{r.setHeader('Content-Type',q.url.endsWith('.png')?'image/png':q.url.endsWith('.js')?'application/javascript':'text/html');r.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390}]){
 await page.setViewportSize(size);await page.evaluate(()=>{__dofTest.newRun();__dofTest.setCombo(5);__dofTest.showDice('monster','basic')});await page.waitForTimeout(240);
 const outer=await page.locator('.encounterPanel').boundingBox(),large=await page.locator('.encounterPanel .cardArtwork').boundingBox();assert(Math.abs(large.height/outer.height-.46)<.01);assert(outer.y>=0&&outer.y+outer.height<size.height);
 await page.screenshot({path:'/tmp/modular-intro-'+size.width+'.png'});
 const corner=await page.locator('.encounterPanel .cardArtwork').evaluate(e=>getComputedStyle(e).borderTopWidth);
 await page.evaluate(()=>{window.aperture=document.querySelector('.encounterPanel .cardArtwork');window.artMutations=0;window.obs=new MutationObserver(ms=>{artMutations+=ms.filter(m=>m.type==='childList'&&m.target===aperture).length});obs.observe(aperture,{childList:true});});
 // Real swipe starts existing dice animation and collapses the same aperture.
 await page.mouse.move(8,100);await page.mouse.down();await page.mouse.move(80,100,{steps:4});await page.mouse.up();await page.waitForTimeout(230);
 const compact=await page.locator('.encounterPanel .cardArtwork').boundingBox();assert(Math.abs(compact.height/outer.height-.13)<.01);assert.deepEqual(await page.locator('.encounterPanel').boundingBox(),outer);assert.equal(await page.locator('.encounterPanel .cardArtwork').evaluate(e=>getComputedStyle(e).borderTopWidth),corner);assert(await page.evaluate(()=>aperture===document.querySelector('.encounterPanel .cardArtwork')&&artMutations===0));
 await page.waitForFunction(()=>__dofTest.serializeRun().pending.encounter?.phase==='preview');await page.waitForTimeout(600);const die=await page.locator('#die').boundingBox();assert(die.width>=72&&die.height>=72);assert(die.y>=compact.y+compact.height);await page.waitForFunction(()=>__dofTest.serializeRun().pending.encounter?.phase==='preview');await page.waitForTimeout(600);assert.equal(await page.locator('.encounterPanel button:visible').count(),1);const action=await page.locator('#rerollButton').boundingBox();assert(action.y>die.y+die.height&&action.y+action.height<size.height);await page.screenshot({path:'/tmp/modular-dice-'+size.width+'.png'});
 await page.evaluate(()=>{obs.disconnect();__dofTest.newRun();__dofTest.inspectItem('consumable',__dofTest.state().relics.consumable)});await page.waitForTimeout(220);const info=await page.locator('.itemChoicePanel').boundingBox(),art=await page.locator('.itemChoicePanel .cardArtwork').boundingBox();assert(Math.abs(art.height/info.height-.46)<.01);await page.screenshot({path:'/tmp/modular-item-'+size.width+'.png'});await page.locator('#itemChoice').tap({position:{x:3,y:3}});
 }
 await page.setViewportSize({width:844,height:390});await page.evaluate(()=>{for(const id of ['doll','eye','blood']){__dofTest.acquireTrinket(id);__dofTest.closeItemCard()}__dofTest.acquireTrinket('horseshoe')});await page.waitForSelector('#replaceSelected:visible');await page.locator('.replaceTrinket[data-item="eye"]').click();assert(await page.locator('.replaceTrinket[data-item="eye"] input').isChecked());const choices=await page.locator('#replaceTrinkets').boundingBox(),confirm=await page.locator('#replaceSelected').boundingBox();assert(choices.y+choices.height<confirm.y);assert(confirm.height>=44&&confirm.y+confirm.height<=390);await page.screenshot({path:'/tmp/modular-replace.png'});await page.locator('#replaceSelected').click();
 await page.evaluate(()=>{__dofTest.showCodex();__dofTest.openCodexDetail('trinket:horseshoe')});const card=await page.locator('#codexCard').boundingBox(),art=await page.locator('#codexCard .cardArtwork').boundingBox();assert(Math.abs(art.height/card.height-.46)<.01);assert.equal(await page.locator('#codexCard button').count(),0);
 assert(await page.locator('#codexCard .cardArtClip').evaluate(e=>getComputedStyle(e).overflow==='hidden'));assert(await page.locator('#codexCard .cardArtwork').evaluate(e=>getComputedStyle(e).borderImageSlice==='80'));await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#codexCard .cardArtwork').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 assert.deepEqual(errors,[]);console.log('PASS fixed outer bounds; large/compact apertures, unchanged corners/nodes, die space, item/Codex large art, landscape replacement, reduced motion and no runtime errors');
 }finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
