const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'application/javascript':req.url.endsWith('.png')?'image/png':'text/html');res.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;await page.goto(url);
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('dof.activeRun'))),state=()=>page.evaluate(()=>__dofTest.state()),snap=()=>page.evaluate(()=>__dofTest.serializeRun());const resume=async()=>{await page.reload();await page.locator('#continueRun').click()};
 assert.equal(await page.locator('#resumeOverlay').isVisible(),false);assert(await page.evaluate(()=>__dofTest.validateSave(__dofTest.serializeRun())));
 await page.evaluate(()=>{const t=__dofTest;t.setCombo(5.6789);t.gainFate(.001);t.setGold(1234);t.setFloor(17);t.setVitals(2,true);t.setConsumable('coin');t.useConsumable(true);t.setConsumable('ward');t.useConsumable(true);t.acquireTrinket('eye');t.closeItemCard();t.acquireTrinket('blood');t.closeItemCard();t.saveRun()});
 let before=await snap();assert(await page.evaluate(()=>__dofTest.validateSave(__dofTest.serializeRun())));await page.reload();assert.equal(await page.locator('#continueRun').isVisible(),true);await page.screenshot({path:'/tmp/dof-continue.png'});
 // Starting another run requires confirmation; cancel leaves bytes untouched.
 const raw=await page.evaluate(()=>localStorage.getItem('dof.activeRun'));await page.locator('#newSavedRun').click();await page.locator('#cancelNewRun').click();assert.equal(await page.evaluate(()=>localStorage.getItem('dof.activeRun')),raw);await page.locator('#continueRun').click();let after=await snap();for(const k of ['run','floor','relicState','fateGate','pending'])assert.deepEqual(after[k],before[k],k+' exact restore');
 console.log('PASS exact floor/resources/effects/FATE precision restore, validation and cancel-safe startup; size',Buffer.byteLength(JSON.stringify(before)),'bytes');
 // Explicit confirmed replacement and learned flags remain independent.
 await page.evaluate(()=>localStorage.setItem('dof.learnedScavenge','1'));await page.reload();await page.locator('#newSavedRun').click();await page.locator('#confirmNewRun').click();assert.equal((await state()).floorNo,1);assert.equal((await state()).gold,0);assert.equal(await page.evaluate(()=>localStorage.getItem('dof.learnedScavenge')),'1');await resume();assert.equal((await state()).floorNo,1);
 // Reserve a result before any swipe. Reload before/after consequence never rerolls/reapplies it.
 for(const [type,kind] of [['monster','basic'],['monster','thief'],['monster','spirit'],['trap','basic'],['heal','basic']]){
  await page.evaluate(({type,kind})=>{const t=__dofTest;t.newRun();t.setGold(1000);t.setCombo(6);t.setVitals(3,false);window.rng=Math.random;Math.random=()=>0;t.showDice(type,kind);Math.random=rng},{type,kind});
  const reserved=(await read()).pending.encounter;assert.equal(reserved.roll,1);await resume();assert.equal((await read()).pending.encounter.roll,1);await page.evaluate(({type,kind})=>{__dofTest.setMonster(kind);__dofTest.resolveDice(type,1)},{type,kind});before=await read();assert.equal(before.pending.encounter.phase,'resolved');await resume();after=await snap();assert.deepEqual(after.run,before.run);assert.deepEqual(after.relicState,before.relicState);assert.equal(after.pending.encounter.roll,1);await page.evaluate(()=>__dofTest.continueEncounter());assert.equal((await read()).pending.encounter,null);
 }
 console.log('PASS fixed Monster/Thief/Ghost/Trap/Shrine outcomes across ready and resolved reloads');
 // A pre-existing clue is durable even before its delayed visual feedback.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();localStorage.setItem('dof.learnedScavenge','1');const s=t.state(),id=s.rooms[s.currentId].links.find(id=>id!==s.exitId);t.markVisited([id]);t.setRoomFixture(id,{scavengeOpportunity:{roll:.8,resolved:false,passiveLead:false}});window.leadId=id;t.revealClue(s.currentId,id,'loot')});before=await read();const lead=before.floor.rooms.find(r=>r.attentionActive).id;assert(before.floor.rooms[lead].scavengeOpportunity);await resume();assert((await state()).rooms[lead].attentionActive);await page.evaluate(id=>{const t=__dofTest;t.setCurrent(id);t.scavenge(id)},lead);before=await read();await resume();assert.deepEqual((await snap()).run,before.run);assert((await state()).rooms[lead].attentionResolved);assert(!(await state()).rooms[lead].attentionActive);
 // Fourth Trinket and occupied Consumable slot reconstruct their choices without replaying acquisition.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();for(const id of ['doll','eye','blood']){t.acquireTrinket(id);t.closeItemCard()}t.acquireTrinket('horseshoe')});before=await read();assert(before.pending.cards.active.decision);await resume();assert.equal(await page.locator('#acquisitionReveal').count(),0);assert.equal(await page.locator('#replaceTrinkets button').count(),3);assert.deepEqual((await state()).relics.trinkets,['doll','eye','blood']);await page.locator('.replaceTrinket[data-item="eye"]').click();await resume();assert.deepEqual((await state()).relics.trinkets,['doll','blood','horseshoe']);await page.evaluate(()=>__dofTest.offerConsumable('flask'));await resume();assert((await state()).cards.active.decision);await page.locator('#takeItem').click();await resume();assert.equal((await state()).relics.consumable,'flask');assert.equal((await state()).cards.active,null);
 console.log('PASS finite clue/opportunity restore and pending replacement decisions without acquisition duplication');
 // Generated branch topology and current position persist even below its access threshold.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();for(let i=0;i<200;i++){t.setCombo(5);t.setFloor(8);const s=t.state(),g=s.fateGate;if(g&&g.branchIds.length>1){t.setRoomFixture(g.parentId,{visited:true,searched:true,eventResolved:true});t.setCurrent(g.parentId);t.setRoomFixture(g.roomId,{event:'empty'});t.setCombo(g.requirement);t.enter(g.roomId);t.setCombo(1);t.saveRun();return}}throw Error('no branch')});before=await read();await resume();after=await snap();assert.deepEqual(after.floor,before.floor);assert.deepEqual(after.fateGate,before.fateGate);await page.evaluate(id=>__dofTest.enter(id),before.fateGate.parentId);assert.equal((await state()).currentId,before.fateGate.parentId);
 // Altar seen/dismissed and spent state are exact, with no repeated first-show or healing.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();for(let i=0;i<100;i++){t.setFloor(5);const s=t.state();if(s.altarRoom!==null){t.setCurrent(s.altarRoom);t.setRoomFixture(s.altarRoom,{searched:true,eventResolved:true});t.setVitals(1,false);t.setCombo(6);t.openAltar(s.altarRoom);t.closeItemCard();return}}});before=await read();await resume();assert.equal((await state()).cards.active,null);assert.deepEqual((await snap()).floor,before.floor);await page.evaluate(()=>{const t=__dofTest;t.openAltar(t.state().currentId);t.sacrificeAltar()});before=await read();await resume();assert.equal((await state()).hp,2);assert.equal((await state()).combo,1);assert.deepEqual((await snap()).floor,before.floor);
 console.log('PASS exact Gate interior/directional exit and unused/spent Altar restore');
 // Auto-walk checkpoints each hop, never its intended destination or a partial hold.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state();t.markVisited(s.rooms.filter(r=>r.active).map(r=>r.id));t.setCurrent(s.startId);t.saveRun();t.travel(s.exitId)});await page.waitForFunction(()=>__dofTest.state().currentId!==__dofTest.state().startId);before=await read();await page.reload();const stopped=await read();await page.locator('#continueRun').click();assert.equal((await state()).currentId,stopped.floor.currentId);assert.equal((await state()).fastTraveling,false);const current=(await state()).currentId;await page.waitForTimeout(400);assert.equal((await state()).currentId,current);
 // Lifecycle flushes the detached safe snapshot rather than uncommitted test mutations.
 before=await read();await page.evaluate(()=>{__dofTest.setGold(999999);window.dispatchEvent(new Event('pagehide'))});assert.deepEqual(await read(),before);await resume();assert.equal((await state()).gold,before.run.gold);
 // Protection resolves before death status; closing during the lethal beat cannot revive.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.acquireTrinket('doll');t.closeItemCard();t.setVitals(1,false);t.setCombo(7);t.resolveDice('trap',1)});before=await read();assert.equal(before.status,'active');await resume();assert.equal((await state()).hp,1);assert.equal((await state()).combo,1);assert(!(await state()).relics.trinkets.includes('doll'));await page.evaluate(()=>{__dofTest.continueEncounter();__dofTest.resolveDice('trap',1)});assert.equal((await read()).status,'ended');await page.reload();assert.equal(await page.locator('#resumeOverlay').isVisible(),false);assert.equal((await state()).hp,3);
 console.log('PASS hop interruption, detached lifecycle snapshot, Doll survival and death invalidation');
 // Per-floor usage and current-room protections survive without replaying hooks.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.acquireTrinket('blood');t.closeItemCard();t.setVitals(1,false);t.resolveDice('monster',5);t.continueEncounter();t.setConsumable('bargain');t.useConsumable(true);t.setConsumable('coin');t.useConsumable(true);t.beginRoomEffects(t.state().currentId,true);t.saveRun()});before=await read();assert(before.relicState.floorUsed.blood);assert.equal(before.relicState.bargainRoom,before.floor.currentId);await resume();assert.deepEqual((await snap()).relicState,before.relicState);assert.deepEqual((await snap()).run,before.run);
 await page.evaluate(()=>{const t=__dofTest;t.newRun();const s=t.state();t.markVisited(s.rooms.filter(r=>r.active&&!t.inGateBranch(r.id)).map(r=>r.id));t.awardPerfectFloor()});before=await read();assert(before.floor.floorPerfectAwarded);await resume();assert.equal(await page.evaluate(()=>__dofTest.awardPerfectFloor()),false);assert.deepEqual((await snap()).run,before.run);
 console.log('PASS current-room effects, used Vampire Blood and no duplicate Perfect Floor');
 // Save-version compatibility is independent of gameVersion; invalid bytes are quarantined.
 const valid=await snap();valid.gameVersion='2.99-compatible';assert(await page.evaluate(s=>__dofTest.validateSave(s)&&__dofTest.restoreRun(s),valid));await page.evaluate(()=>__dofTest.flushRun());await page.reload();assert.equal((await read()).gameVersion,'2.99-compatible');await page.locator('#continueRun').click();assert.equal((await state()).hp,valid.run.hp);
 const corrupt=['{broken',JSON.stringify({...valid,saveVersion:99}),JSON.stringify({...valid,floor:{...valid.floor,rooms:null}}),JSON.stringify({...valid,floor:{...valid.floor,currentId:99}}),JSON.stringify({...valid,relicState:{...valid.relicState,trinkets:['fake']}}),JSON.stringify({...valid,fateGate:{roomId:90,branchIds:[90]}})];
 for(const raw of corrupt){const c=await browser.newContext();await c.addInitScript(raw=>localStorage.setItem('dof.activeRun',raw),raw);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);assert.equal(await p.locator('#resumeOverlay').isVisible(),false);assert.equal(await p.evaluate(()=>__dofTest.state().hp),3);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('dof.activeRun.invalid')).raw),raw);await c.close()}
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota')}});const p=await blocked.newPage();const warnings=[];p.on('console',m=>{if(m.type()==='warning')warnings.push(m.text())});await p.goto(url);await p.evaluate(()=>{__dofTest.newRun();__dofTest.newRun();__dofTest.saveRun()});assert.equal(await p.evaluate(()=>__dofTest.state().hp),3);assert.equal(warnings.filter(m=>m.includes('[DOF save]')).length,1);await blocked.close();
 assert.deepEqual(errors,[]);console.log('PASS compatible versions, malformed/unsupported saves, storage failure and no runtime errors');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
