const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((q,r)=>fs.readFile(path.join(root,q.url==='/'?'index.html':q.url),(err,data)=>{r.setHeader('Content-Type',q.url.endsWith('.png')?'image/png':q.url.endsWith('.js')?'application/javascript':'text/html');r.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.PWA_BROWSER});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const save=()=>page.evaluate(()=>__dofTest.serializeRun()),state=()=>page.evaluate(()=>__dofTest.state());
 async function resume(){await page.reload();await page.locator('#continueRun').click()}
 async function accept(){await page.locator('#diceOverlay').tap({position:{x:4,y:4}})}
 async function offer(id){await page.evaluate(id=>{__dofTest.offerConsumable(id);__dofTest.finishItemReveal()},id)}
 // Archive eligibility is independent from ordinary generation. Exercise actual Scavenge path.
 await page.evaluate(()=>{localStorage.setItem("dof.learnedScavenge","1");const t=__dofTest;t.setRoomFixture(t.state().currentId,{scavenged:false,scavengeOpportunity:{roll:.99,resolved:false,passiveLead:false}});t.scavenge(t.state().currentId,.99)});
 assert((await page.evaluate(()=>__dofTest.codex())).discovered['hazard:trap']);await page.evaluate(()=>__dofTest.clearPending());
 for(const type of ['altar','chest']){
  await page.evaluate(type=>{const t=__dofTest;t.newRun();const id=t.state().currentId;t.setRoomFixture(id,type==='altar'?{event:'altar',altarCardSeen:false,altarUsed:false}:{event:'chest',chest:{kind:'consumable',itemId:'flask',cardSeen:false,opened:false}})},type);
  const id='discovery:'+type;assert(!(await page.evaluate(()=>__dofTest.codex())).discovered[id]);
  await page.evaluate(type=>{const t=__dofTest;t[type==='altar'?'openAltar':'openChestCard'](t.state().currentId,true)},type);assert((await page.evaluate(()=>__dofTest.codex())).discovered[id]);await page.evaluate(()=>__dofTest.closeItemCard());
 }
 console.log('PASS Archive: Scavenge Trap, encountered Altar/Chest; creation alone does not discover');
 // One physical dropped item and one inventory slot. Pending pickup is semantic save state.
 await page.evaluate(()=>{__dofTest.newRun();__dofTest.setConsumable('ward')});await offer('flask');await page.locator('#takeItem').tap();let s=await save(),id=s.floor.currentId;
 assert.equal(s.relicState.consumable,'flask');assert.equal(s.floor.rooms[id].droppedConsumable,'ward');assert.equal(s.pending.cards.active,null);await resume();assert.equal((await save()).floor.rooms[id].droppedConsumable,'ward');
 await page.locator('.cell.current').tap();assert.equal((await save()).pending.cards.active.mode,'pickup');assert.equal(await page.locator('#itemName').innerText(),'Trap Ward');await resume();assert.equal((await save()).pending.cards.active.mode,'pickup');await page.locator('#takeItem').tap();s=await save();assert.equal(s.relicState.consumable,'ward');assert.equal(s.floor.rooms[id].droppedConsumable,'flask');
 assert.equal(await page.evaluate(()=>__dofTest.offerConsumable('charm')),false);assert.equal((await save()).floor.rooms[id].droppedConsumable,'flask');
 await page.evaluate(()=>{const t=__dofTest,s=t.state(),next=s.rooms[s.currentId].links.find(id=>!t.inGateBranch(id));window.dropOrigin=s.currentId;t.setRoomFixture(next,{event:'empty',eventResolved:true});t.markVisited([next]);t.enter(next);t.travel(dropOrigin)});await page.waitForFunction(()=>!__dofTest.state().fastTraveling);assert.equal((await state()).currentId,id);assert(await page.locator('#itemChoice').isHidden());
 await page.evaluate(()=>__dofTest.setConsumable(null));await page.locator('.cell.current .droppedItem').tap();await page.locator('#takeItem').tap();s=await save();assert.equal(s.relicState.consumable,'flask');assert.equal(s.floor.rooms[id].droppedConsumable,null);await resume();assert.equal((await save()).relicState.consumable,'flask');
 // A dropped item must not make an underlying reusable landmark inaccessible.
 await page.evaluate(()=>{const t=__dofTest,id=t.state().currentId;t.setRoomFixture(id,{event:'garden',contentState:{seen:true,resolved:false,consumed:false},droppedConsumable:'ward'})});await page.locator('.cell.current').tap();assert.equal(await page.locator('#itemName').innerText(),'Trap Ward');await page.evaluate(()=>{__dofTest.setConsumable(null);__dofTest.chooseConsumable(true)});await page.locator('.cell.current').tap();assert.equal(await page.locator('#itemName').innerText(),'Small Garden');await page.locator('#itemChoice').tap({position:{x:4,y:4}});await page.evaluate(()=>__dofTest.newFloor());assert(!(await save()).floor.rooms.some(r=>r.droppedConsumable));
 console.log('PASS dropped/held exchange, pending pickup reload, occupied-room protection, empty-slot pickup, quiet auto-walk, feature access, floor-local lifetime');
 // Fortune has one semantic negative transaction: Thief theft. The exact preview commits once.
 for(const active of [false,true])for(const roll of [1,2,3,4]){
  await page.evaluate(({active,roll})=>{const t=__dofTest;t.newRun();t.setGold(480);t.setCombo(5);if(active){t.setConsumable('coin');t.useConsumable(true);t.beginRoomEffects(t.state().currentId,true)}const random=Math.random;Math.random=()=>(roll-.5)/6;t.showDice('monster','thief');Math.random=random;t.revealOutcome()},{active,roll});s=await save();const loss=roll<=3?Math.floor(480*[0,.25,.15,.07][roll])*(active?2:1):0;
  assert.equal(s.pending.encounter.preview.after.gold,480-loss);assert.equal(s.run.gold,480);if(active&&loss)assert.match(s.pending.encounter.preview.text,/theft ×2/);await resume();assert.equal((await save()).pending.encounter.preview.after.gold,480-loss);await accept();assert.equal((await save()).run.gold,480-loss);
 }
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setGold(480);t.setCombo(5);t.setConsumable('coin');t.useConsumable(true);t.beginRoomEffects(t.state().currentId,true);Math.originalRandom=Math.random;Math.random=()=>0;t.showDice('monster','thief');Math.random=Math.originalRandom;t.revealOutcome()});await page.waitForSelector('#rerollButton:not([hidden])');await page.evaluate(()=>{const random=Math.random;Math.random=()=>.99;__dofTest.rerollOutcome();Math.random=random});await resume();await page.evaluate(()=>__dofTest.revealOutcome());assert.equal((await save()).run.gold,480);await accept();assert((await save()).run.gold>480);
 await page.evaluate(()=>__dofTest.setGold(37));assert.equal((await save()).run.gold,37);
 console.log('PASS Fortune Thief preview/commit/reload, accepted and rejected theft, final doubled reward, direct Gold setter unaffected');
 // Amnesia commits real state first and erases only its presentation, far-to-near.
 async function amnesia(){await page.evaluate(()=>{const t=__dofTest;t.newRun();t.markVisited(t.state().rooms.filter(r=>r.active).map(r=>r.id));t.setCombo(5);const random=Math.random;Math.random=()=>0;t.showDice('stones');Math.random=random;t.revealOutcome()});await accept()}
 await amnesia();const world=(await save()).floor.rooms;const wipe=await page.evaluate(()=>__dofTest.memoryWipe());assert.equal(wipe.phase,'running');s=await save();assert.equal(s.run.conditions.amnesia,10);assert(!wipe.order.includes(s.floor.currentId));const distances={[s.floor.currentId]:0},q=[s.floor.currentId];for(let i=0;i<q.length;i++)for(const n of world[q[i]].links){if(distances[n]===undefined){distances[n]=distances[q[i]]+1;q.push(n)}};for(let i=1;i<wipe.order.length;i++)assert(distances[wipe.order[i-1]]>=distances[wipe.order[i]]);
 const current=s.floor.currentId;await page.evaluate(()=>{const t=__dofTest;t.enter(t.state().rooms[t.state().currentId].links[0]);t.travel(t.state().rooms[t.state().currentId].links[0])});assert.equal((await save()).floor.currentId,current);assert(await page.locator('#board').evaluate(e=>e.inert));assert.equal(await page.evaluate(()=>__dofTest.inspectItem('consumable',__dofTest.state().relics.consumable)),false);
 await page.waitForTimeout(150);assert(await page.locator('.cell.memoryForgotten').count()>0);assert.equal(await page.locator('.cell.current.memoryForgotten').count(),0);await page.waitForFunction(()=>!__dofTest.memoryWipe());assert.deepEqual((await save()).floor.rooms,world);assert.equal((await save()).run.conditions.amnesia,10);assert(!(await page.locator('#board').evaluate(e=>e.inert)));await page.evaluate(()=>{__dofTest.clearConditions();__dofTest.update()});assert.equal(await page.locator('#activeMap .cell').count(),world.filter(r=>r.active&&r.known).length);
 await amnesia();await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));assert.equal(await page.evaluate(()=>__dofTest.memoryWipe()),null);await resume();assert.equal((await save()).run.conditions.amnesia,10);assert.equal(await page.evaluate(()=>__dofTest.memoryWipe()),null);
 await page.emulateMedia({reducedMotion:'reduce'});await amnesia();assert.equal(await page.evaluate(()=>__dofTest.memoryWipe()),null);await page.emulateMedia({reducedMotion:'no-preference'});
 console.log('PASS progressive memory order, input lock, unchanged topology/visited/countdown, expiry presentation, lifecycle cancellation/reload, reduced motion');
 // Shared shelf clearance: long description/action, ordinary actions, replacement, Chest hold.
 for(const size of [{width:390,height:844},{width:320,height:568},{width:568,height:320}]){
  await page.setViewportSize(size);
  for(const type of ['garden','food','corpse','flower','hole']){await page.evaluate(type=>{const t=__dofTest;t.newRun();t.setVitals(2,false);t.setRoomFixture(t.state().currentId,{event:type,contentState:{seen:false,resolved:false,consumed:false}});t.openContent(t.state().currentId,true)},type);const panel=await page.locator('.itemChoicePanel').boundingBox(),action=await page.locator('#contentAction').boundingBox();assert(action.y+action.height<=panel.y+panel.height*.90);assert(action.y>=panel.y);}
  await page.screenshot({path:'/tmp/refinement-action-'+size.width+'.png'});
 }
 await page.setViewportSize({width:390,height:844});
 // Lethal sequence invalidates run before the conclusion. Guard requires a fresh input.
 async function die(){await page.evaluate(()=>{const t=__dofTest;t.newRun();t.acquireTrinket('eye');t.closeItemCard();t.setConsumable('ward');t.setVitals(1,false);t.resolveDice('trap',1)});await page.waitForFunction(()=>__dofTest.state().gameOver)}
 await die();await page.screenshot({path:'/tmp/refinement-death.png'});assert(await page.locator('#deathConclusion').isVisible());assert(await page.locator('#overlay').isHidden());assert.equal(await page.locator('#hud').evaluate(e=>getComputedStyle(e).visibility),'hidden');assert(await page.locator('#board').isVisible());assert(await page.locator('#trinkets [data-item="eye"]').isVisible());assert(await page.locator('#consumableSlot').isVisible());assert(await page.locator('#consumableSlot').isDisabled());assert(await page.locator('#relicBar').evaluate(e=>e.inert));assert.equal(await page.evaluate(()=>__dofTest.showCodex()),false);assert.equal(await page.evaluate(()=>__dofTest.loadRun()),null);
 await page.locator('#deathConclusion').dispatchEvent('pointerup',{pointerId:1});await page.locator('#deathConclusion').dispatchEvent('click');assert(await page.locator('#deathConclusion').isVisible());await page.locator('#deathConclusion').tap();assert(await page.locator('#deathConclusion').isVisible());await page.waitForTimeout(350);await page.locator('#deathConclusion').tap();assert(await page.locator('#overlay').isVisible());await page.locator('#again').tap();assert.equal((await state()).gameOver,false);assert(await page.locator('#hud').isVisible());
 await die();await page.reload();assert(await page.locator('#continueRun').isHidden());assert.equal((await state()).gameOver,false);assert.equal((await state()).hp,3);
 await page.evaluate(()=>{const t=__dofTest;t.acquireTrinket('doll');t.closeItemCard();t.setVitals(1,false);t.resolveDice('trap',1)});await page.waitForTimeout(1300);assert.equal((await state()).gameOver,false);assert.equal((await state()).hp,1);assert(!(await state()).relics.trinkets.includes('doll'));assert(await page.locator('#deathConclusion').isHidden());
 assert.deepEqual(errors,[]);console.log('PASS death conclusion/guard/final inventory/inactive controls, existing résumé/New Run, ended reload, Doll rescue; no runtime errors');
 }finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
