const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>fs.readFile(path.join(root,req.url==='/'?'index.html':req.url),(err,data)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'application/javascript':'text/html');res.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,...(process.env.PWA_BROWSER?{executablePath:process.env.PWA_BROWSER}:{})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const holdReroll=async()=>{const b=await page.locator('#rerollButton').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForTimeout(700);await page.mouse.up()};
 const state=()=>page.evaluate(()=>__dofTest.state()),save=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('dof.activeRun'))),resume=async()=>{await page.reload();await page.locator('#continueRun').click()};
 // Read-only previews must match the unchanged resolver for every face/table and protection.
 const cases=await page.evaluate(()=>{const t=__dofTest;let count=0;for(const [type,kind] of [['monster','basic'],['monster','thief'],['monster','spirit'],['trap','basic'],['heal','basic']])for(let roll=1;roll<=6;roll++)for(const mode of ['plain','shield','doll','bargain','full','hooks']){
 t.newRun();t.setGold(1234);t.setCombo(5.67);t.setVitals(mode==='full'?3:1,mode==='shield'||mode==='full');if(mode==='doll'){t.acquireTrinket('doll');t.closeItemCard()}if(mode==='bargain'){t.setConsumable('bargain');t.useConsumable(true)}if(mode==='hooks'){for(const id of ['blood','horseshoe']){t.acquireTrinket(id);t.closeItemCard()}t.setConsumable('coin');t.useConsumable(true);t.beginRoomEffects(t.state().currentId,true)}t.setMonster(kind);
 const before=t.serializeRun(),preview=t.previewOutcome(type,roll,kind),untouched=t.serializeRun();if(JSON.stringify(before.run)!==JSON.stringify(untouched.run)||JSON.stringify(before.relicState)!==JSON.stringify(untouched.relicState))throw Error('preview mutation');t.resolveDice(type,roll);const actual=t.state();for(const key of Object.keys(preview.after))if(Math.abs(Number(actual[key])-Number(preview.after[key]))>1e-9)throw Error([type,kind,roll,mode,key,actual[key],preview.after[key]].join(' / '));count++;
 }t.newRun();return count});assert.equal(cases,180);console.log('PASS 180 preview/commit table cases, protection and perfect/victory hooks, no preview mutations');
 async function preview(type,kind,roll,fate=5){await page.evaluate(({type,kind,roll,fate})=>{const t=__dofTest;t.newRun();t.setCombo(fate);t.setGold(1000);t.setVitals(1,false);const rng=Math.random;Math.random=()=>((roll-1)/6)+.001;t.showDice(type,kind);Math.random=rng;t.revealOutcome()},{type,kind,roll,fate})}

 // UX hotfix: the whole Reroll target owns its gesture, including canceled releases.
 await preview('monster','thief',1);await page.waitForTimeout(600);let untouched=await save();
 await page.locator('#rerollButton').tap();assert.deepEqual((await save()).pending,untouched.pending);assert.equal((await state()).combo,5);
 let b=await page.locator('#rerollButton').boundingBox();const x=b.x+b.width/2,y=b.y+b.height/2;
 await page.mouse.move(x,y);await page.mouse.down();await page.waitForTimeout(200);assert.equal(await page.locator('#rerollButton.holding').count(),1);await page.mouse.up();await page.waitForTimeout(500);assert.deepEqual((await save()).pending,untouched.pending);assert.equal((await state()).gold,1000);
 await page.mouse.down();await page.mouse.move(b.x-20,y);await page.waitForTimeout(700);await page.mouse.up();assert.deepEqual((await save()).pending,untouched.pending);
 // Real touch drag/cancel and additional contact: no payment or tap-to-accept leakage.
 const cdp=await page.context().newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x-25,y,id:1}]});await page.waitForTimeout(700);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual((await save()).pending,untouched.pending);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:2},{x:x+10,y:y+5,id:3}]});await page.waitForTimeout(700);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.deepEqual((await save()).pending,untouched.pending);
 // Closing/backgrounding an incomplete hold preserves the choice and drops progress.
 await page.mouse.move(x,y);await page.mouse.down();await page.waitForTimeout(200);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await page.waitForTimeout(700);await page.mouse.up();assert.deepEqual((await save()).pending,untouched.pending);await resume();await page.waitForTimeout(400);assert.equal(await page.locator('#rerollButton.holding').count(),0);assert.deepEqual((await save()).pending,untouched.pending);
 await page.locator('#rerollButton').focus();await page.keyboard.press('Enter');assert.deepEqual((await save()).pending,untouched.pending);
 await page.locator('#diceOverlay').tap({position:{x:5,y:5}});assert.equal((await state()).gold,750);assert.equal((await save()).pending.encounter,null);
 console.log('PASS quick tap, short hold, mouse/touch drag, multitouch, canceled keyboard and interrupted-hold persistence');
 for(const fate of [1,1.99,2,3,5,10,20]){await preview('monster','basic',1,fate);assert.equal(await page.locator('#rerollButton').isVisible(),false);await page.waitForTimeout(390);assert.equal(await page.locator('#rerollButton').isVisible(),fate>=2);if(fate>=2){const expected=1+(fate-1)*.75;assert.equal((await save()).pending.encounter.offer.after,expected);assert.match(await page.locator('#rerollCost').innerText(),new RegExp(expected.toFixed(2).replace('.','\\.')))}}
 console.log('PASS minimum, cost examples, delayed appearance and actual cost text');
 for(const [type,kind] of [['monster','basic'],['monster','thief'],['monster','spirit'],['trap','basic'],['heal','basic']]){
  await preview(type,kind,1);await page.evaluate(()=>{const t=__dofTest,s=t.serializeRun();s.run.hp=3;s.pending.encounter.phase='ready';t.restoreRun(s);t.revealOutcome()});const expected=(await save()).pending.encounter.preview.after;await page.locator('#diceOverlay').tap({position:{x:5,y:5}});for(const key of Object.keys(expected))assert.equal((await state())[key],expected[key]);const accepted=await save();await page.evaluate(()=>__dofTest.continueEncounter());assert.deepEqual((await save()).run,accepted.run);
 }
 console.log('PASS original acceptance commits once across all five encounter paths');

 for(const [type,kind] of [['monster','basic'],['monster','thief'],['monster','spirit'],['trap','basic'],['heal','basic']]){
 await preview(type,kind,1);await page.waitForTimeout(390);const original=await save();await resume();await page.waitForTimeout(390);assert.deepEqual((await save()).pending.encounter,original.pending.encounter);assert.equal((await state()).hp,1);assert.equal((await state()).gold,1000);assert.equal((await state()).combo,5);
 await page.evaluate(()=>{window.randomBefore=Math.random;Math.random=()=>.999});await holdReroll();await page.evaluate(()=>{Math.random=randomBefore;document.getElementById('rerollButton').click()});const paid=await save();assert.equal(paid.run.combo,4);assert.equal(paid.pending.encounter.roll,6);assert.equal(paid.pending.encounter.rerollUsed,true);assert.equal(paid.pending.encounter.phase,'ready');assert.equal((await state()).hp,1);assert.equal((await state()).gold,1000);
 // Mandatory close during second animation: no refund, regenerated face, or second chance.
 await resume();assert.equal((await save()).pending.encounter.roll,6);assert.equal((await state()).combo,4);await page.waitForFunction(()=>__dofTest.serializeRun().pending.encounter?.phase==='preview');await page.waitForTimeout(390);assert.equal(await page.locator('#rerollButton').isVisible(),false);const final=await save();assert.equal(final.pending.encounter.rerollUsed,true);const expected=final.pending.encounter.preview.after;
 await page.locator('#diceOverlay').tap({position:{x:5,y:5}});const actual=await state();for(const k of Object.keys(expected))assert.equal(actual[k],expected[k],type+' final '+k);assert.equal((await save()).pending.encounter,null);await resume();assert.equal((await state()).combo,expected.combo);assert.equal((await state()).gold,expected.gold);
 }
 console.log('PASS each archetype: choice reload, single payment, second-animation reload, final acceptance once');
 // Rejected perfect result must never fire Horseshoe/Blood; lethal final invokes Doll only on accept.
 await preview('monster','basic',6);await page.evaluate(()=>{const t=__dofTest;const s=t.serializeRun();s.relicState.trinkets=['horseshoe','blood','doll'];s.pending.encounter.phase='ready';t.restoreRun(s);t.revealOutcome()});await page.waitForTimeout(390);assert.equal((await state()).gold,1000);assert.equal((await state()).hp,1);await page.evaluate(()=>{window.rng=Math.random;Math.random=()=>0});await holdReroll();await page.evaluate(()=>Math.random=rng);await page.waitForFunction(()=>__dofTest.serializeRun().pending.encounter?.phase==='preview');assert((await state()).relics.trinkets.includes('doll'));await page.locator('#diceOverlay').tap({position:{x:5,y:5}});assert.equal((await state()).hp,1);assert.equal((await state()).combo,1);assert.equal((await state()).gold,1000);assert(!(await state()).relics.trinkets.includes('doll'));assert.equal((await state()).deathPending,false);
 // Ward resolves before any die/choice exists.
 await page.evaluate(()=>{const t=__dofTest;t.newRun();t.setConsumable('ward');t.useConsumable(true);t.showDice('trap')});assert.equal((await save()).pending.encounter,null);assert.equal((await state()).relics.wardArmed,false);
 // Old ready/resolved v1 saves remain valid and do not replay already committed results.
 await preview('monster','basic',4);let old=await save();old.gameVersion='2.16.3.1';old.pending.encounter={type:'monster',roomId:old.floor.currentId,monsterKind:'basic',roll:4,phase:'ready'};assert(await page.evaluate(s=>__dofTest.restoreRun(s),old));await page.evaluate(()=>__dofTest.flushRun());await resume();assert.equal(await page.locator('#buildVersion').innerText(),'V2.20');assert.equal((await save()).pending.encounter.roll,4);
 await page.evaluate(()=>__dofTest.resolveDice('monster',4));old=await save();const gold=old.run.gold;await resume();assert.equal((await state()).gold,gold);assert.equal(await page.locator('#rerollButton').isVisible(),false);
 // Phone layout, real keyboard control and no layout shift/overflow.
 await preview('monster','thief',1);const dieBefore=await page.locator('.dieStage').boundingBox();await page.waitForTimeout(390);assert.deepEqual(await page.locator('.dieStage').boundingBox(),dieBefore);for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(200);const b=await page.locator('#rerollButton').boundingBox();assert(b.width>=44&&b.height>=44);assert(b.x>=0&&b.x+b.width<=size.width);assert(b.y>=0&&b.y+b.height<=size.height);const detail=await page.locator('#diceDetail').boundingBox(),die=await page.locator('#die').boundingBox();assert(b.y>=detail.y+detail.height);assert(b.y>=die.y+die.height);assert(await page.locator('#rerollButton').evaluate(el=>!document.querySelector('.dieStage').contains(el)));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/dof-reroll.png'});await page.locator('#rerollButton').focus();await page.keyboard.down('Enter');await page.waitForTimeout(700);await page.keyboard.up('Enter');assert((await save()).pending.encounter.rerollUsed);
 assert.deepEqual(errors,[]);console.log('PASS rejected perfect, lethal Doll, Ward, old-save compatibility, keyboard/mobile overlay and no runtime errors');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
