const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');const server=http.createServer((q,r)=>fs.readFile(path.join(root,q.url==='/'?'index.html':q.url),(err,data)=>{r.setHeader('Content-Type',q.url.endsWith('.png')?'image/png':q.url.endsWith('.js')?'application/javascript':'text/html');r.writeHead(err?404:200).end(data)}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.PWA_BROWSER});const context=await browser.newContext({viewport:{width:320,height:568},isMobile:true,hasTouch:true});await context.addInitScript(require('./movement-test-helpers.cjs').clock);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const generate=()=>{const t=__dofTest,random=Math.random,out=[];for(let seed=1;seed<=200;seed++){let n=seed;Math.random=()=>((n=Math.imul(n,1664525)+1013904223>>>0)/4294967296);t.newRun();t.setFloor(3+seed%20);const s=t.serializeRun();s.floor.rooms.forEach(r=>delete r.shape);out.push({floor:s.floor,gate:s.fateGate,fortune:s.run.combo})}Math.random=random;return out};
 // Frozen SHA-256 of 200 seeded floor/content snapshots, excluding shape only. Updated for the Fate Compass reward-pool addition.
 assert.equal(require('node:crypto').createHash('sha256').update(JSON.stringify(await page.evaluate(generate))).digest('hex'),'f3826ac74e0d73c1806ab3b0f204673c3cd6bb90584a27ba9ba6516e56a98734');
 const stats=await page.evaluate(()=>{const t=__dofTest,counts={};for(let i=0;i<300;i++){t.setFloor(3+i%20);for(const r of t.serializeRun().floor.rooms)if(r.active){counts[r.shape.kind]=(counts[r.shape.kind]||0)+1;const a=t.chooseRoomShape(r,123),b=t.chooseRoomShape({...r,event:'heal',droppedConsumable:'flask'},123);if(JSON.stringify(a)!==JSON.stringify(b))throw Error('content dependency')}}return counts});assert.equal(Object.keys(stats).length,4);
 const weighted=await page.evaluate(()=>{const t=__dofTest;t.newRun();const groups={terminal:[39],straight:[39,41],corner:[39,31],three:[39,41,31],four:[39,41,31,49]},out={};for(const [name,links] of Object.entries(groups)){out[name]=[0,0,0,0];for(let seed=0;seed<20000;seed++){const r={id:40,x:4,y:4,links},s=t.chooseRoomShape(r,seed);out[name][t.shapeConfig.kinds.indexOf(s.kind)]++;if(name==='straight'&&s.orientation!=='horizontal')throw Error('axis')} }return out});for(const [name,c] of Object.entries(weighted)){const weights=await page.evaluate(name=>__dofTest.shapeConfig.weights[name],name);c.forEach((v,i)=>assert(Math.abs(v/200-weights[i])<2))}
 console.log('PASS 200 seeded floors stable topology/content/RNG with Compass reward pool; all shapes, topology weights and content independence',stats);
 const kinds=['square','rectangle','round','chamfered'];
 for(const a of kinds)for(const b of kinds){await page.evaluate(({a,b})=>{const t=__dofTest;t.newRun();const s=t.state(),id=s.rooms[s.currentId].links.find(id=>id!==s.exitId);window.target=id;t.setRoomFixture(s.currentId,{shape:{kind:a,orientation:'horizontal'}});t.setRoomFixture(id,{shape:{kind:b,orientation:'vertical'},event:'empty',visited:true,searched:true,known:true,eventResolved:true});t.applyCondition('slowed');t.saveRun();t.update()}, {a,b});const old=await page.evaluate(()=>__dofTest.serializeRun());await page.locator('.cell[data-id="'+await page.evaluate(()=>target)+'"]').tap();assert.equal(await page.evaluate(()=>__dofTest.travelState().duration),550);await page.evaluate(()=>travelProgress(.5));assert(await page.evaluate(()=>{const t=__dofTest,travel=t.travelState(),map=document.getElementById('activeMap'),light=map.querySelector('.travelLight'),a=map.querySelector('.cell[data-id="'+travel.from+'"] .floor').getBoundingClientRect(),b=map.querySelector('.cell[data-id="'+travel.to+'"] .floor').getBoundingClientRect(),l=light.getBoundingClientRect();return Math.abs(l.x+l.width/2-(a.x+a.width/2+b.x+b.width/2)/2)<1&&Math.abs(l.y+l.height/2-(a.y+a.height/2+b.y+b.height/2)/2)<1}));assert.equal(await page.evaluate(()=>__dofTest.state().currentId),old.floor.currentId);await page.evaluate(()=>walkTick());assert.equal(await page.evaluate(()=>__dofTest.state().currentId),await page.evaluate(()=>target));assert.equal(await page.evaluate(()=>__dofTest.conditions().slowed),9)}
 console.log('PASS all 16 moving-light shape combinations, immediate travel, unchanged Slowed duration and one arrival/countdown');
 await page.evaluate(()=>{const t=__dofTest;for(let i=0;i<100;i++){t.setFloor(12);if(t.serializeRun().floor.layers.length===2)break}t.markVisited(t.state().rooms.filter(r=>r.active).map(r=>r.id));t.saveRun()});
 const saved=await page.evaluate(()=>__dofTest.serializeRun());await page.reload();await page.locator('#continueRun').click();assert.deepEqual((await page.evaluate(()=>__dofTest.serializeRun())).floor.rooms,saved.floor.rooms);
 await page.evaluate(()=>{const t=__dofTest,r=t.state().rooms.find(r=>r.stairTo!==undefined&&r.layerId===0);t.setCurrent(r.id);t.traverseStairs()});await page.waitForTimeout(600);assert.deepEqual((await page.evaluate(()=>__dofTest.serializeRun())).floor.rooms.map(r=>r.shape),saved.floor.rooms.map(r=>r.shape));assert(await page.locator('.inactiveLayer').evaluate(e=>e.inert));
 await page.evaluate(()=>{const t=__dofTest;t.setRoomFixture(t.state().currentId,{droppedConsumable:'flask'});t.update()});
 for(const [width,height] of [[320,568],[390,844],[430,932],[844,390],[1280,800]]){await page.setViewportSize({width,height});await page.evaluate(()=>__dofTest.update());const geometry=await page.evaluate(()=>{const board=document.getElementById('board'),m=__dofTest.mapGeometry(board.clientWidth,board.clientHeight),c=__dofTest.mapGeometryConfig;
 if(Math.abs(m.stepX-board.clientWidth/9)>0.01)throw Error('horizontal spacing changed');
 if(Math.abs(m.stepY-board.clientHeight/9*Math.max(.7,Math.min(1,board.clientWidth/board.clientHeight)))>.01)throw Error('vertical spacing');
 const active=__dofTest.state().rooms.filter(r=>r.active),xs=active.map(r=>r.x),ys=active.map(r=>r.y);if(Math.abs(m.originX+(Math.min(...xs)+Math.max(...xs))*m.stepX/2-board.clientWidth/2)>.01||Math.abs(m.originY+(Math.min(...ys)+Math.max(...ys))*m.stepY/2-board.clientHeight/2)>.01)throw Error('centering');
 if(m.base>Math.min(board.clientWidth,board.clientHeight)*.072*1.3+.01)throw Error('scale');
 if(Math.min(m.stepX,m.stepY)-m.base*__dofTest.shapeConfig.rectangleLong<1.99)throw Error('rectangle clearance');
 const marker=document.querySelector('#activeMap .current .droppedItem'),item=marker.getBoundingClientRect(),target=marker.parentElement.getBoundingClientRect();if(item.left<target.left||item.right>target.right||item.top<target.top||item.bottom>target.bottom)throw Error('item hitbox escapes room');const cells=[...document.querySelectorAll('#activeMap .cell')];let collisions=0;for(let i=0;i<cells.length;i++)for(let j=i+1;j<cells.length;j++){const a=cells[i].getBoundingClientRect(),b=cells[j].getBoundingClientRect();if(Math.min(a.right,b.right)>Math.max(a.left,b.left)&&Math.min(a.bottom,b.bottom)>Math.max(a.top,b.top))collisions++}return{metrics:{board:[board.clientWidth,board.clientHeight],base:m.base,x:m.stepX,y:m.stepY},collisions,types:cells.map(c=>c.dataset.shape),joins:[...document.querySelectorAll('#activeMap .link')].every(e=>{const a=document.querySelector('#activeMap .cell[data-id="'+e.dataset.from+'"] .floor').getBoundingClientRect(),b=document.querySelector('#activeMap .cell[data-id="'+e.dataset.to+'"] .floor').getBoundingClientRect(),l=e.getBoundingClientRect();return Math.floor((+e.dataset.from%81)/9)===Math.floor((+e.dataset.to%81)/9)?Math.abs(l.left-Math.min(a.right,b.right))<2&&Math.abs(l.right-Math.max(a.left,b.left))<2:Math.abs(l.top-Math.min(a.bottom,b.bottom))<2&&Math.abs(l.bottom-Math.max(a.top,b.top))<2})}});assert.equal(geometry.collisions,0);assert(geometry.joins);console.log(width+'×'+height,geometry.metrics);await page.screenshot({path:'/tmp/shapes-'+width+'.png'})}
 await page.evaluate(()=>{const t=__dofTest,s=t.state(),r=s.rooms.find(r=>r.active&&r.layerId===Math.floor(s.currentId/81)&&r.id!==s.currentId);window.hiddenRoom=r.id;t.setRoomFixture(r.id,{shape:{kind:'rectangle',orientation:'vertical'},searched:false,visited:false,known:true});t.update()});assert.equal(await page.locator('.cell[data-id="'+await page.evaluate(()=>hiddenRoom)+'"]').getAttribute('data-shape'),'square');
 await page.evaluate(()=>{__dofTest.applyCondition('amnesia');__dofTest.update()});assert(await page.locator('#activeMap .cell:not(.current)').evaluateAll(cs=>cs.every(c=>c.dataset.shape==='square')));assert.deepEqual((await page.evaluate(()=>__dofTest.serializeRun())).floor.rooms.map(r=>r.links),saved.floor.rooms.map(r=>r.links));
 assert.deepEqual(errors,[]);console.log('PASS save/reload, reciprocal layers, silhouettes/joins/targets in 5 sizes, frontier/Amnesia privacy');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
